package gov.geoplatform.uasdm.processing;

@com.runwaysdk.business.ClassSignature(hash = -1424214871)
/**
 * This class is generated automatically.
 * DO NOT MAKE CHANGES TO IT - THEY WILL BE OVERWRITTEN
 * Custom business logic should be added to FargateProcessingTask.java
 *
 * @author Autogenerated by RunwaySDK
 */
public  class FargateProcessingTaskQuery extends gov.geoplatform.uasdm.bus.WorkflowTaskQuery

{

  public FargateProcessingTaskQuery(com.runwaysdk.query.QueryFactory componentQueryFactory)
  {
    super(componentQueryFactory);
    if (this.getComponentQuery() == null)
    {
      com.runwaysdk.business.BusinessQuery businessQuery = componentQueryFactory.businessQuery(this.getClassType());

       this.setBusinessQuery(businessQuery);
    }
  }

  public FargateProcessingTaskQuery(com.runwaysdk.query.ValueQuery valueQuery)
  {
    super(valueQuery);
    if (this.getComponentQuery() == null)
    {
      com.runwaysdk.business.BusinessQuery businessQuery = new com.runwaysdk.business.BusinessQuery(valueQuery, this.getClassType());

       this.setBusinessQuery(businessQuery);
    }
  }

  public String getClassType()
  {
    return gov.geoplatform.uasdm.processing.FargateProcessingTask.CLASS;
  }
  public com.runwaysdk.query.SelectableChar getConfigurationJson()
  {
    return getConfigurationJson(null);

  }
 
  public com.runwaysdk.query.SelectableChar getConfigurationJson(String alias)
  {
    return (com.runwaysdk.query.SelectableChar)this.getComponentQuery().get(gov.geoplatform.uasdm.processing.FargateProcessingTask.CONFIGURATIONJSON, alias, null);

  }
 
  public com.runwaysdk.query.SelectableChar getConfigurationJson(String alias, String displayLabel)
  {
    return (com.runwaysdk.query.SelectableChar)this.getComponentQuery().get(gov.geoplatform.uasdm.processing.FargateProcessingTask.CONFIGURATIONJSON, alias, displayLabel);

  }
  public com.runwaysdk.query.SelectableChar getProcessFilenameArray()
  {
    return getProcessFilenameArray(null);

  }
 
  public com.runwaysdk.query.SelectableChar getProcessFilenameArray(String alias)
  {
    return (com.runwaysdk.query.SelectableChar)this.getComponentQuery().get(gov.geoplatform.uasdm.processing.FargateProcessingTask.PROCESSFILENAMEARRAY, alias, null);

  }
 
  public com.runwaysdk.query.SelectableChar getProcessFilenameArray(String alias, String displayLabel)
  {
    return (com.runwaysdk.query.SelectableChar)this.getComponentQuery().get(gov.geoplatform.uasdm.processing.FargateProcessingTask.PROCESSFILENAMEARRAY, alias, displayLabel);

  }
  public com.runwaysdk.query.SelectableChar getProcessingType()
  {
    return getProcessingType(null);

  }
 
  public com.runwaysdk.query.SelectableChar getProcessingType(String alias)
  {
    return (com.runwaysdk.query.SelectableChar)this.getComponentQuery().get(gov.geoplatform.uasdm.processing.FargateProcessingTask.PROCESSINGTYPE, alias, null);

  }
 
  public com.runwaysdk.query.SelectableChar getProcessingType(String alias, String displayLabel)
  {
    return (com.runwaysdk.query.SelectableChar)this.getComponentQuery().get(gov.geoplatform.uasdm.processing.FargateProcessingTask.PROCESSINGTYPE, alias, displayLabel);

  }
  public com.runwaysdk.query.SelectableChar getTaskArn()
  {
    return getTaskArn(null);

  }
 
  public com.runwaysdk.query.SelectableChar getTaskArn(String alias)
  {
    return (com.runwaysdk.query.SelectableChar)this.getComponentQuery().get(gov.geoplatform.uasdm.processing.FargateProcessingTask.TASKARN, alias, null);

  }
 
  public com.runwaysdk.query.SelectableChar getTaskArn(String alias, String displayLabel)
  {
    return (com.runwaysdk.query.SelectableChar)this.getComponentQuery().get(gov.geoplatform.uasdm.processing.FargateProcessingTask.TASKARN, alias, displayLabel);

  }
  public com.runwaysdk.query.SelectableChar getTaskDefinitionArn()
  {
    return getTaskDefinitionArn(null);

  }
 
  public com.runwaysdk.query.SelectableChar getTaskDefinitionArn(String alias)
  {
    return (com.runwaysdk.query.SelectableChar)this.getComponentQuery().get(gov.geoplatform.uasdm.processing.FargateProcessingTask.TASKDEFINITIONARN, alias, null);

  }
 
  public com.runwaysdk.query.SelectableChar getTaskDefinitionArn(String alias, String displayLabel)
  {
    return (com.runwaysdk.query.SelectableChar)this.getComponentQuery().get(gov.geoplatform.uasdm.processing.FargateProcessingTask.TASKDEFINITIONARN, alias, displayLabel);

  }
  /**  
   * Returns an iterator of Business objects that match the query criteria specified
   * on this query object. 
   * @return iterator of Business objects that match the query criteria specified
   * on this query object.
   */
  public com.runwaysdk.query.OIterator<? extends FargateProcessingTask> getIterator()
  {
    this.checkNotUsedInValueQuery();
    String sqlStmt;
    if (_limit != null && _skip != null)
    {
      sqlStmt = this.getComponentQuery().getSQL(_limit, _skip);
    }
    else
    {
      sqlStmt = this.getComponentQuery().getSQL();
    }
    java.util.Map<String, com.runwaysdk.query.ColumnInfo> columnInfoMap = this.getComponentQuery().getColumnInfoMap();

    java.sql.ResultSet results = com.runwaysdk.dataaccess.database.Database.query(sqlStmt);
    return new com.runwaysdk.business.BusinessIterator<FargateProcessingTask>(this.getComponentQuery().getMdEntityIF(), columnInfoMap, results);
  }


/**
 * Interface that masks all type unsafe query methods and defines all type safe methods.
 * This type is used when a join is performed on this class as a reference.
 **/
  public interface FargateProcessingTaskQueryReferenceIF extends gov.geoplatform.uasdm.bus.WorkflowTaskQuery.WorkflowTaskQueryReferenceIF
  {

    public com.runwaysdk.query.SelectableChar getConfigurationJson();
    public com.runwaysdk.query.SelectableChar getConfigurationJson(String alias);
    public com.runwaysdk.query.SelectableChar getConfigurationJson(String alias, String displayLabel);
    public com.runwaysdk.query.SelectableChar getProcessFilenameArray();
    public com.runwaysdk.query.SelectableChar getProcessFilenameArray(String alias);
    public com.runwaysdk.query.SelectableChar getProcessFilenameArray(String alias, String displayLabel);
    public com.runwaysdk.query.SelectableChar getProcessingType();
    public com.runwaysdk.query.SelectableChar getProcessingType(String alias);
    public com.runwaysdk.query.SelectableChar getProcessingType(String alias, String displayLabel);
    public com.runwaysdk.query.SelectableChar getTaskArn();
    public com.runwaysdk.query.SelectableChar getTaskArn(String alias);
    public com.runwaysdk.query.SelectableChar getTaskArn(String alias, String displayLabel);
    public com.runwaysdk.query.SelectableChar getTaskDefinitionArn();
    public com.runwaysdk.query.SelectableChar getTaskDefinitionArn(String alias);
    public com.runwaysdk.query.SelectableChar getTaskDefinitionArn(String alias, String displayLabel);

    public com.runwaysdk.query.BasicCondition EQ(gov.geoplatform.uasdm.processing.FargateProcessingTask fargateProcessingTask);

    public com.runwaysdk.query.BasicCondition NE(gov.geoplatform.uasdm.processing.FargateProcessingTask fargateProcessingTask);

  }

/**
 * Implements type safe query methods.
 * This type is used when a join is performed on this class as a reference.
 **/
  public static class FargateProcessingTaskQueryReference extends gov.geoplatform.uasdm.bus.WorkflowTaskQuery.WorkflowTaskQueryReference
 implements FargateProcessingTaskQueryReferenceIF

  {

  public FargateProcessingTaskQueryReference(com.runwaysdk.dataaccess.MdAttributeRefDAOIF mdAttributeIF, String attributeNamespace, String definingTableName, String definingTableAlias, com.runwaysdk.dataaccess.MdBusinessDAOIF referenceMdBusinessIF, String referenceTableAlias, com.runwaysdk.query.ComponentQuery rootQuery, java.util.Set<com.runwaysdk.query.Join> tableJoinSet, String alias, String displayLabel)
  {
    super(mdAttributeIF, attributeNamespace, definingTableName, definingTableAlias, referenceMdBusinessIF, referenceTableAlias, rootQuery, tableJoinSet, alias, displayLabel);

  }


    public com.runwaysdk.query.BasicCondition EQ(gov.geoplatform.uasdm.processing.FargateProcessingTask fargateProcessingTask)
    {
      if(fargateProcessingTask == null) return this.EQ((java.lang.String)null);
      return this.EQ(fargateProcessingTask.getOid());
    }

    public com.runwaysdk.query.BasicCondition NE(gov.geoplatform.uasdm.processing.FargateProcessingTask fargateProcessingTask)
    {
      if(fargateProcessingTask == null) return this.NE((java.lang.String)null);
      return this.NE(fargateProcessingTask.getOid());
    }

  public com.runwaysdk.query.SelectableChar getConfigurationJson()
  {
    return getConfigurationJson(null);

  }
 
  public com.runwaysdk.query.SelectableChar getConfigurationJson(String alias)
  {
    return (com.runwaysdk.query.SelectableChar)this.get(gov.geoplatform.uasdm.processing.FargateProcessingTask.CONFIGURATIONJSON, alias, null);

  }
 
  public com.runwaysdk.query.SelectableChar getConfigurationJson(String alias, String displayLabel)
  {
    return (com.runwaysdk.query.SelectableChar)this.get(gov.geoplatform.uasdm.processing.FargateProcessingTask.CONFIGURATIONJSON, alias, displayLabel);

  }
  public com.runwaysdk.query.SelectableChar getProcessFilenameArray()
  {
    return getProcessFilenameArray(null);

  }
 
  public com.runwaysdk.query.SelectableChar getProcessFilenameArray(String alias)
  {
    return (com.runwaysdk.query.SelectableChar)this.get(gov.geoplatform.uasdm.processing.FargateProcessingTask.PROCESSFILENAMEARRAY, alias, null);

  }
 
  public com.runwaysdk.query.SelectableChar getProcessFilenameArray(String alias, String displayLabel)
  {
    return (com.runwaysdk.query.SelectableChar)this.get(gov.geoplatform.uasdm.processing.FargateProcessingTask.PROCESSFILENAMEARRAY, alias, displayLabel);

  }
  public com.runwaysdk.query.SelectableChar getProcessingType()
  {
    return getProcessingType(null);

  }
 
  public com.runwaysdk.query.SelectableChar getProcessingType(String alias)
  {
    return (com.runwaysdk.query.SelectableChar)this.get(gov.geoplatform.uasdm.processing.FargateProcessingTask.PROCESSINGTYPE, alias, null);

  }
 
  public com.runwaysdk.query.SelectableChar getProcessingType(String alias, String displayLabel)
  {
    return (com.runwaysdk.query.SelectableChar)this.get(gov.geoplatform.uasdm.processing.FargateProcessingTask.PROCESSINGTYPE, alias, displayLabel);

  }
  public com.runwaysdk.query.SelectableChar getTaskArn()
  {
    return getTaskArn(null);

  }
 
  public com.runwaysdk.query.SelectableChar getTaskArn(String alias)
  {
    return (com.runwaysdk.query.SelectableChar)this.get(gov.geoplatform.uasdm.processing.FargateProcessingTask.TASKARN, alias, null);

  }
 
  public com.runwaysdk.query.SelectableChar getTaskArn(String alias, String displayLabel)
  {
    return (com.runwaysdk.query.SelectableChar)this.get(gov.geoplatform.uasdm.processing.FargateProcessingTask.TASKARN, alias, displayLabel);

  }
  public com.runwaysdk.query.SelectableChar getTaskDefinitionArn()
  {
    return getTaskDefinitionArn(null);

  }
 
  public com.runwaysdk.query.SelectableChar getTaskDefinitionArn(String alias)
  {
    return (com.runwaysdk.query.SelectableChar)this.get(gov.geoplatform.uasdm.processing.FargateProcessingTask.TASKDEFINITIONARN, alias, null);

  }
 
  public com.runwaysdk.query.SelectableChar getTaskDefinitionArn(String alias, String displayLabel)
  {
    return (com.runwaysdk.query.SelectableChar)this.get(gov.geoplatform.uasdm.processing.FargateProcessingTask.TASKDEFINITIONARN, alias, displayLabel);

  }
  }

/**
 * Interface that masks all type unsafe query methods and defines all type safe methods.
 * This type is used when a join is performed on this class as a reference.
 **/
  public interface FargateProcessingTaskQueryMultiReferenceIF extends gov.geoplatform.uasdm.bus.WorkflowTaskQuery.WorkflowTaskQueryMultiReferenceIF
  {

    public com.runwaysdk.query.SelectableChar getConfigurationJson();
    public com.runwaysdk.query.SelectableChar getConfigurationJson(String alias);
    public com.runwaysdk.query.SelectableChar getConfigurationJson(String alias, String displayLabel);
    public com.runwaysdk.query.SelectableChar getProcessFilenameArray();
    public com.runwaysdk.query.SelectableChar getProcessFilenameArray(String alias);
    public com.runwaysdk.query.SelectableChar getProcessFilenameArray(String alias, String displayLabel);
    public com.runwaysdk.query.SelectableChar getProcessingType();
    public com.runwaysdk.query.SelectableChar getProcessingType(String alias);
    public com.runwaysdk.query.SelectableChar getProcessingType(String alias, String displayLabel);
    public com.runwaysdk.query.SelectableChar getTaskArn();
    public com.runwaysdk.query.SelectableChar getTaskArn(String alias);
    public com.runwaysdk.query.SelectableChar getTaskArn(String alias, String displayLabel);
    public com.runwaysdk.query.SelectableChar getTaskDefinitionArn();
    public com.runwaysdk.query.SelectableChar getTaskDefinitionArn(String alias);
    public com.runwaysdk.query.SelectableChar getTaskDefinitionArn(String alias, String displayLabel);

    public com.runwaysdk.query.Condition containsAny(gov.geoplatform.uasdm.processing.FargateProcessingTask ... fargateProcessingTask);
    public com.runwaysdk.query.Condition notContainsAny(gov.geoplatform.uasdm.processing.FargateProcessingTask ... fargateProcessingTask);
    public com.runwaysdk.query.Condition containsAll(gov.geoplatform.uasdm.processing.FargateProcessingTask ... fargateProcessingTask);
    public com.runwaysdk.query.Condition notContainsAll(gov.geoplatform.uasdm.processing.FargateProcessingTask ... fargateProcessingTask);
    public com.runwaysdk.query.Condition containsExactly(gov.geoplatform.uasdm.processing.FargateProcessingTask ... fargateProcessingTask);
  }

/**
 * Implements type safe query methods.
 * This type is used when a join is performed on this class as a reference.
 **/
  public static class FargateProcessingTaskQueryMultiReference extends gov.geoplatform.uasdm.bus.WorkflowTaskQuery.WorkflowTaskQueryMultiReference
 implements FargateProcessingTaskQueryMultiReferenceIF

  {

  public FargateProcessingTaskQueryMultiReference(com.runwaysdk.dataaccess.MdAttributeMultiReferenceDAOIF mdAttributeIF, String attributeNamespace, String definingTableName, String definingTableAlias, String mdMultiReferenceTableName, com.runwaysdk.dataaccess.MdBusinessDAOIF referenceMdBusinessIF, String referenceTableAlias, com.runwaysdk.query.ComponentQuery rootQuery, java.util.Set<com.runwaysdk.query.Join> tableJoinSet, String alias, String displayLabel)
  {
    super(mdAttributeIF, attributeNamespace, definingTableName, definingTableAlias, mdMultiReferenceTableName, referenceMdBusinessIF, referenceTableAlias, rootQuery, tableJoinSet, alias, displayLabel);

  }



    public com.runwaysdk.query.Condition containsAny(gov.geoplatform.uasdm.processing.FargateProcessingTask ... fargateProcessingTask)  {

      String[] itemIdArray = new String[fargateProcessingTask.length]; 

      for (int i=0; i<fargateProcessingTask.length; i++)
      {
        itemIdArray[i] = fargateProcessingTask[i].getOid();
      }

      return this.containsAny(itemIdArray);
  }

    public com.runwaysdk.query.Condition notContainsAny(gov.geoplatform.uasdm.processing.FargateProcessingTask ... fargateProcessingTask)  {

      String[] itemIdArray = new String[fargateProcessingTask.length]; 

      for (int i=0; i<fargateProcessingTask.length; i++)
      {
        itemIdArray[i] = fargateProcessingTask[i].getOid();
      }

      return this.notContainsAny(itemIdArray);
  }

    public com.runwaysdk.query.Condition containsAll(gov.geoplatform.uasdm.processing.FargateProcessingTask ... fargateProcessingTask)  {

      String[] itemIdArray = new String[fargateProcessingTask.length]; 

      for (int i=0; i<fargateProcessingTask.length; i++)
      {
        itemIdArray[i] = fargateProcessingTask[i].getOid();
      }

      return this.containsAll(itemIdArray);
  }

    public com.runwaysdk.query.Condition notContainsAll(gov.geoplatform.uasdm.processing.FargateProcessingTask ... fargateProcessingTask)  {

      String[] itemIdArray = new String[fargateProcessingTask.length]; 

      for (int i=0; i<fargateProcessingTask.length; i++)
      {
        itemIdArray[i] = fargateProcessingTask[i].getOid();
      }

      return this.notContainsAll(itemIdArray);
  }

    public com.runwaysdk.query.Condition containsExactly(gov.geoplatform.uasdm.processing.FargateProcessingTask ... fargateProcessingTask)  {

      String[] itemIdArray = new String[fargateProcessingTask.length]; 

      for (int i=0; i<fargateProcessingTask.length; i++)
      {
        itemIdArray[i] = fargateProcessingTask[i].getOid();
      }

      return this.containsExactly(itemIdArray);
  }
  public com.runwaysdk.query.SelectableChar getConfigurationJson()
  {
    return getConfigurationJson(null);

  }
 
  public com.runwaysdk.query.SelectableChar getConfigurationJson(String alias)
  {
    return (com.runwaysdk.query.SelectableChar)this.get(gov.geoplatform.uasdm.processing.FargateProcessingTask.CONFIGURATIONJSON, alias, null);

  }
 
  public com.runwaysdk.query.SelectableChar getConfigurationJson(String alias, String displayLabel)
  {
    return (com.runwaysdk.query.SelectableChar)this.get(gov.geoplatform.uasdm.processing.FargateProcessingTask.CONFIGURATIONJSON, alias, displayLabel);

  }
  public com.runwaysdk.query.SelectableChar getProcessFilenameArray()
  {
    return getProcessFilenameArray(null);

  }
 
  public com.runwaysdk.query.SelectableChar getProcessFilenameArray(String alias)
  {
    return (com.runwaysdk.query.SelectableChar)this.get(gov.geoplatform.uasdm.processing.FargateProcessingTask.PROCESSFILENAMEARRAY, alias, null);

  }
 
  public com.runwaysdk.query.SelectableChar getProcessFilenameArray(String alias, String displayLabel)
  {
    return (com.runwaysdk.query.SelectableChar)this.get(gov.geoplatform.uasdm.processing.FargateProcessingTask.PROCESSFILENAMEARRAY, alias, displayLabel);

  }
  public com.runwaysdk.query.SelectableChar getProcessingType()
  {
    return getProcessingType(null);

  }
 
  public com.runwaysdk.query.SelectableChar getProcessingType(String alias)
  {
    return (com.runwaysdk.query.SelectableChar)this.get(gov.geoplatform.uasdm.processing.FargateProcessingTask.PROCESSINGTYPE, alias, null);

  }
 
  public com.runwaysdk.query.SelectableChar getProcessingType(String alias, String displayLabel)
  {
    return (com.runwaysdk.query.SelectableChar)this.get(gov.geoplatform.uasdm.processing.FargateProcessingTask.PROCESSINGTYPE, alias, displayLabel);

  }
  public com.runwaysdk.query.SelectableChar getTaskArn()
  {
    return getTaskArn(null);

  }
 
  public com.runwaysdk.query.SelectableChar getTaskArn(String alias)
  {
    return (com.runwaysdk.query.SelectableChar)this.get(gov.geoplatform.uasdm.processing.FargateProcessingTask.TASKARN, alias, null);

  }
 
  public com.runwaysdk.query.SelectableChar getTaskArn(String alias, String displayLabel)
  {
    return (com.runwaysdk.query.SelectableChar)this.get(gov.geoplatform.uasdm.processing.FargateProcessingTask.TASKARN, alias, displayLabel);

  }
  public com.runwaysdk.query.SelectableChar getTaskDefinitionArn()
  {
    return getTaskDefinitionArn(null);

  }
 
  public com.runwaysdk.query.SelectableChar getTaskDefinitionArn(String alias)
  {
    return (com.runwaysdk.query.SelectableChar)this.get(gov.geoplatform.uasdm.processing.FargateProcessingTask.TASKDEFINITIONARN, alias, null);

  }
 
  public com.runwaysdk.query.SelectableChar getTaskDefinitionArn(String alias, String displayLabel)
  {
    return (com.runwaysdk.query.SelectableChar)this.get(gov.geoplatform.uasdm.processing.FargateProcessingTask.TASKDEFINITIONARN, alias, displayLabel);

  }
  }
}
