package gov.geoplatform.uasdm.lidar;

@com.runwaysdk.business.ClassSignature(hash = 277554709)
/**
 * This class is generated automatically.
 * DO NOT MAKE CHANGES TO IT - THEY WILL BE OVERWRITTEN
 * Custom business logic should be added to LidarProcessingTask.java
 *
 * @author Autogenerated by RunwaySDK
 */
public class LidarProcessingTaskQueryDTO extends gov.geoplatform.uasdm.bus.WorkflowTaskQueryDTO
{
@SuppressWarnings("unused")
private static final long serialVersionUID = 277554709;

  protected LidarProcessingTaskQueryDTO(String type)
  {
    super(type);
  }

@SuppressWarnings("unchecked")
public java.util.List<? extends gov.geoplatform.uasdm.lidar.LidarProcessingTaskDTO> getResultSet()
{
  return (java.util.List<? extends gov.geoplatform.uasdm.lidar.LidarProcessingTaskDTO>)super.getResultSet();
}
}
