package gov.geoplatform.uasdm.bus;

@com.runwaysdk.business.ClassSignature(hash = -1326491562)
/**
 * This class is generated automatically.
 * DO NOT MAKE CHANGES TO IT - THEY WILL BE OVERWRITTEN
 * Custom business logic should be added to AbstractUploadTask.java
 *
 * @author Autogenerated by RunwaySDK
 */
public class AbstractUploadTaskQueryDTO extends gov.geoplatform.uasdm.bus.AbstractWorkflowTaskQueryDTO
{
@SuppressWarnings("unused")
private static final long serialVersionUID = -1326491562;

  protected AbstractUploadTaskQueryDTO(String type)
  {
    super(type);
  }

@SuppressWarnings("unchecked")
public java.util.List<? extends gov.geoplatform.uasdm.bus.AbstractUploadTaskDTO> getResultSet()
{
  return (java.util.List<? extends gov.geoplatform.uasdm.bus.AbstractUploadTaskDTO>)super.getResultSet();
}
}
