package gov.geoplatform.uasdm.bus;

@com.runwaysdk.business.ClassSignature(hash = -1573516235)
/**
 * This class is generated automatically.
 * DO NOT MAKE CHANGES TO IT - THEY WILL BE OVERWRITTEN
 * Custom business logic should be added to Collection.java
 *
 * @author Autogenerated by RunwaySDK
 */
public  class CollectionQuery extends gov.geoplatform.uasdm.bus.UasComponentQuery

{

  public CollectionQuery(com.runwaysdk.query.QueryFactory componentQueryFactory)
  {
    super(componentQueryFactory);
    if (this.getComponentQuery() == null)
    {
      com.runwaysdk.business.BusinessQuery businessQuery = componentQueryFactory.businessQuery(this.getClassType());

       this.setBusinessQuery(businessQuery);
    }
  }

  public CollectionQuery(com.runwaysdk.query.ValueQuery valueQuery)
  {
    super(valueQuery);
    if (this.getComponentQuery() == null)
    {
      com.runwaysdk.business.BusinessQuery businessQuery = new com.runwaysdk.business.BusinessQuery(valueQuery, this.getClassType());

       this.setBusinessQuery(businessQuery);
    }
  }

  public String getClassType()
  {
    return gov.geoplatform.uasdm.bus.Collection.CLASS;
  }
  public com.runwaysdk.query.SelectableInteger getImageHeight()
  {
    return getImageHeight(null);

  }
 
  public com.runwaysdk.query.SelectableInteger getImageHeight(String alias)
  {
    return (com.runwaysdk.query.SelectableInteger)this.getComponentQuery().get(gov.geoplatform.uasdm.bus.Collection.IMAGEHEIGHT, alias, null);

  }
 
  public com.runwaysdk.query.SelectableInteger getImageHeight(String alias, String displayLabel)
  {
    return (com.runwaysdk.query.SelectableInteger)this.getComponentQuery().get(gov.geoplatform.uasdm.bus.Collection.IMAGEHEIGHT, alias, displayLabel);

  }
  public com.runwaysdk.query.SelectableInteger getImageWidth()
  {
    return getImageWidth(null);

  }
 
  public com.runwaysdk.query.SelectableInteger getImageWidth(String alias)
  {
    return (com.runwaysdk.query.SelectableInteger)this.getComponentQuery().get(gov.geoplatform.uasdm.bus.Collection.IMAGEWIDTH, alias, null);

  }
 
  public com.runwaysdk.query.SelectableInteger getImageWidth(String alias, String displayLabel)
  {
    return (com.runwaysdk.query.SelectableInteger)this.getComponentQuery().get(gov.geoplatform.uasdm.bus.Collection.IMAGEWIDTH, alias, displayLabel);

  }
  public com.runwaysdk.query.SelectableBoolean getMetadataUploaded()
  {
    return getMetadataUploaded(null);

  }
 
  public com.runwaysdk.query.SelectableBoolean getMetadataUploaded(String alias)
  {
    return (com.runwaysdk.query.SelectableBoolean)this.getComponentQuery().get(gov.geoplatform.uasdm.bus.Collection.METADATAUPLOADED, alias, null);

  }
 
  public com.runwaysdk.query.SelectableBoolean getMetadataUploaded(String alias, String displayLabel)
  {
    return (com.runwaysdk.query.SelectableBoolean)this.getComponentQuery().get(gov.geoplatform.uasdm.bus.Collection.METADATAUPLOADED, alias, displayLabel);

  }
  public gov.geoplatform.uasdm.bus.PrivilegeTypeQuery.AllPrivilegeTypeQueryIF getPrivilegeType()
  {
    return getPrivilegeType(null);

  }
 
  public gov.geoplatform.uasdm.bus.PrivilegeTypeQuery.AllPrivilegeTypeQueryIF getPrivilegeType(String alias)
  {

    com.runwaysdk.dataaccess.MdAttributeDAOIF mdAttributeIF = this.getComponentQuery().getMdAttributeROfromMap(gov.geoplatform.uasdm.bus.Collection.PRIVILEGETYPE);

    return (gov.geoplatform.uasdm.bus.PrivilegeTypeQuery.AllPrivilegeTypeQueryIF)this.getComponentQuery().internalAttributeFactory(gov.geoplatform.uasdm.bus.Collection.PRIVILEGETYPE, mdAttributeIF, this, alias, null);

  }
 
  public gov.geoplatform.uasdm.bus.PrivilegeTypeQuery.AllPrivilegeTypeQueryIF getPrivilegeType(String alias, String displayLabel)
  {

    com.runwaysdk.dataaccess.MdAttributeDAOIF mdAttributeIF = this.getComponentQuery().getMdAttributeROfromMap(gov.geoplatform.uasdm.bus.Collection.PRIVILEGETYPE);

    return (gov.geoplatform.uasdm.bus.PrivilegeTypeQuery.AllPrivilegeTypeQueryIF)this.getComponentQuery().internalAttributeFactory(gov.geoplatform.uasdm.bus.Collection.PRIVILEGETYPE, mdAttributeIF, this, alias, displayLabel);

  }
  protected com.runwaysdk.query.AttributeEnumeration enumerationFactory( com.runwaysdk.dataaccess.MdAttributeEnumerationDAOIF mdAttributeIF, String attributeNamespace, String definingTableName, String definingTableAlias,  String mdEnumerationTableName, com.runwaysdk.dataaccess.MdBusinessDAOIF masterListMdBusinessIF, String masterListTalbeAlias, com.runwaysdk.query.ComponentQuery rootQuery, java.util.Set<com.runwaysdk.query.Join> tableJoinSet, String userDefinedAlias, String userDefinedDisplayLabel)
  {
    String name = mdAttributeIF.definesAttribute();
    
    if (name.equals(gov.geoplatform.uasdm.bus.Collection.PRIVILEGETYPE)) 
    {
       return new gov.geoplatform.uasdm.bus.PrivilegeTypeQuery.AllPrivilegeTypeQuery((com.runwaysdk.dataaccess.MdAttributeEnumerationDAOIF)mdAttributeIF,  attributeNamespace, definingTableName, definingTableAlias, mdEnumerationTableName, masterListMdBusinessIF, masterListTalbeAlias, rootQuery, tableJoinSet, userDefinedAlias, userDefinedDisplayLabel);
    }
    else 
    {
      return super.enumerationFactory(mdAttributeIF, attributeNamespace, definingTableName, definingTableAlias, mdEnumerationTableName, masterListMdBusinessIF, masterListTalbeAlias, rootQuery, tableJoinSet, userDefinedAlias, userDefinedDisplayLabel);
    }
  }

  /**  
   * Returns an iterator of Business objects that match the query criteria specified
   * on this query object. 
   * @return iterator of Business objects that match the query criteria specified
   * on this query object.
   */
  public com.runwaysdk.query.OIterator<? extends Collection> getIterator()
  {
    this.checkNotUsedInValueQuery();
    String sqlStmt;
    if (_limit != null && _skip != null)
    {
      sqlStmt = this.getComponentQuery().getSQL(_limit, _skip);
    }
    else
    {
      sqlStmt = this.getComponentQuery().getSQL();
    }
    java.util.Map<String, com.runwaysdk.query.ColumnInfo> columnInfoMap = this.getComponentQuery().getColumnInfoMap();

    java.sql.ResultSet results = com.runwaysdk.dataaccess.database.Database.query(sqlStmt);
    return new com.runwaysdk.business.BusinessIterator<Collection>(this.getComponentQuery().getMdEntityIF(), columnInfoMap, results);
  }


  public com.runwaysdk.query.Condition mission()
  {
    com.runwaysdk.query.QueryFactory queryFactory = this.getQueryFactory();
    com.runwaysdk.business.RelationshipQuery relationshipQuery = queryFactory.relationshipQuery(gov.geoplatform.uasdm.bus.MissionHasCollection.CLASS);

    return this.getBusinessQuery().isChildIn(relationshipQuery);
  }


  public com.runwaysdk.query.Condition SUBSELECT_mission()
  {
    com.runwaysdk.query.QueryFactory queryFactory = this.getQueryFactory();
    com.runwaysdk.business.RelationshipQuery relationshipQuery = queryFactory.relationshipQuery(gov.geoplatform.uasdm.bus.MissionHasCollection.CLASS);

    return this.getBusinessQuery().isChildIn_SUBSELECT(relationshipQuery);
  }

  public com.runwaysdk.query.Condition mission(gov.geoplatform.uasdm.bus.MissionHasCollectionQuery missionHasCollectionQuery)
  {
    return this.getBusinessQuery().isChildIn(missionHasCollectionQuery);
  }

  public com.runwaysdk.query.Condition SUBSELECT_mission(gov.geoplatform.uasdm.bus.MissionHasCollectionQuery missionHasCollectionQuery)
  {
    return this.getBusinessQuery().isChildIn_SUBSELECT(missionHasCollectionQuery);
  }

  public com.runwaysdk.query.Condition mission(gov.geoplatform.uasdm.bus.MissionQuery missionQuery)
  {
    com.runwaysdk.query.QueryFactory queryFactory = this.getQueryFactory();
    com.runwaysdk.business.RelationshipQuery relationshipQuery = queryFactory.relationshipQuery(gov.geoplatform.uasdm.bus.MissionHasCollection.CLASS);
    relationshipQuery.AND(relationshipQuery.hasParent(missionQuery));

    return this.getBusinessQuery().isChildIn(relationshipQuery);
  }

  public com.runwaysdk.query.Condition SUBSELECT_mission(gov.geoplatform.uasdm.bus.MissionQuery missionQuery)
  {
    com.runwaysdk.query.QueryFactory queryFactory = this.getQueryFactory();
    com.runwaysdk.business.RelationshipQuery relationshipQuery = queryFactory.relationshipQuery(gov.geoplatform.uasdm.bus.MissionHasCollection.CLASS);
    relationshipQuery.AND(relationshipQuery.hasParent(missionQuery));

    return this.getBusinessQuery().isChildIn_SUBSELECT(relationshipQuery);
  }

  public com.runwaysdk.query.Condition mission(gov.geoplatform.uasdm.bus.MissionQuery missionQuery, gov.geoplatform.uasdm.bus.MissionHasCollectionQuery missionHasCollectionQuery)
  {
    missionHasCollectionQuery.AND(missionHasCollectionQuery.hasParent(missionQuery));
    return this.getBusinessQuery().isChildIn(missionHasCollectionQuery);
  }

  public com.runwaysdk.query.Condition SUBSELECT_mission(gov.geoplatform.uasdm.bus.MissionQuery missionQuery, gov.geoplatform.uasdm.bus.MissionHasCollectionQuery missionHasCollectionQuery)
  {
    missionHasCollectionQuery.AND(missionHasCollectionQuery.hasParent(missionQuery));
    return this.getBusinessQuery().isChildIn_SUBSELECT(missionHasCollectionQuery);
  }


  public com.runwaysdk.query.Condition NOT_IN_mission()
  {
    com.runwaysdk.query.QueryFactory queryFactory = this.getQueryFactory();
    com.runwaysdk.business.RelationshipQuery relationshipQuery = queryFactory.relationshipQuery(gov.geoplatform.uasdm.bus.MissionHasCollection.CLASS);

    return this.getBusinessQuery().isNotChildIn(relationshipQuery);
  }


  public com.runwaysdk.query.Condition SUBSELECT_NOT_IN_mission()
  {
    com.runwaysdk.query.QueryFactory queryFactory = this.getQueryFactory();
    com.runwaysdk.business.RelationshipQuery relationshipQuery = queryFactory.relationshipQuery(gov.geoplatform.uasdm.bus.MissionHasCollection.CLASS);

    return this.getBusinessQuery().isNotChildIn_SUBSELECT(relationshipQuery);
  }

  public com.runwaysdk.query.Condition NOT_IN_mission(gov.geoplatform.uasdm.bus.MissionHasCollectionQuery missionHasCollectionQuery)
  {
    return this.getBusinessQuery().isNotChildIn(missionHasCollectionQuery);
  }

  public com.runwaysdk.query.Condition SUBSELECT_NOT_IN_mission(gov.geoplatform.uasdm.bus.MissionHasCollectionQuery missionHasCollectionQuery)
  {
    return this.getBusinessQuery().isNotChildIn_SUBSELECT(missionHasCollectionQuery);
  }

  public com.runwaysdk.query.Condition NOT_IN_mission(gov.geoplatform.uasdm.bus.MissionQuery missionQuery)
  {
    com.runwaysdk.query.QueryFactory queryFactory = this.getQueryFactory();
    com.runwaysdk.business.RelationshipQuery relationshipQuery = queryFactory.relationshipQuery(gov.geoplatform.uasdm.bus.MissionHasCollection.CLASS);
    relationshipQuery.AND(relationshipQuery.hasParent(missionQuery));

    return this.getBusinessQuery().isNotChildIn(relationshipQuery);
  }

  public com.runwaysdk.query.Condition SUBSELECT_NOT_IN_mission(gov.geoplatform.uasdm.bus.MissionQuery missionQuery)
  {
    com.runwaysdk.query.QueryFactory queryFactory = this.getQueryFactory();
    com.runwaysdk.business.RelationshipQuery relationshipQuery = queryFactory.relationshipQuery(gov.geoplatform.uasdm.bus.MissionHasCollection.CLASS);
    relationshipQuery.AND(relationshipQuery.hasParent(missionQuery));

    return this.getBusinessQuery().isNotChildIn_SUBSELECT(relationshipQuery);
  }

  public com.runwaysdk.query.Condition NOT_IN_mission(gov.geoplatform.uasdm.bus.MissionQuery missionQuery, gov.geoplatform.uasdm.bus.MissionHasCollectionQuery missionHasCollectionQuery)
  {
    missionHasCollectionQuery.AND(missionHasCollectionQuery.hasParent(missionQuery));
    return this.getBusinessQuery().isNotChildIn(missionHasCollectionQuery);
  }

  public com.runwaysdk.query.Condition SUBSELECT_NOT_IN_mission(gov.geoplatform.uasdm.bus.MissionQuery missionQuery, gov.geoplatform.uasdm.bus.MissionHasCollectionQuery missionHasCollectionQuery)
  {
    missionHasCollectionQuery.AND(missionHasCollectionQuery.hasParent(missionQuery));
    return this.getBusinessQuery().isNotChildIn_SUBSELECT(missionHasCollectionQuery);
  }


/**
 * Interface that masks all type unsafe query methods and defines all type safe methods.
 * This type is used when a join is performed on this class as a reference.
 **/
  public interface CollectionQueryReferenceIF extends gov.geoplatform.uasdm.bus.UasComponentQuery.UasComponentQueryReferenceIF
  {

    public com.runwaysdk.query.SelectableInteger getImageHeight();
    public com.runwaysdk.query.SelectableInteger getImageHeight(String alias);
    public com.runwaysdk.query.SelectableInteger getImageHeight(String alias, String displayLabel);
    public com.runwaysdk.query.SelectableInteger getImageWidth();
    public com.runwaysdk.query.SelectableInteger getImageWidth(String alias);
    public com.runwaysdk.query.SelectableInteger getImageWidth(String alias, String displayLabel);
    public com.runwaysdk.query.SelectableBoolean getMetadataUploaded();
    public com.runwaysdk.query.SelectableBoolean getMetadataUploaded(String alias);
    public com.runwaysdk.query.SelectableBoolean getMetadataUploaded(String alias, String displayLabel);
  public gov.geoplatform.uasdm.bus.PrivilegeTypeQuery.AllPrivilegeTypeQueryIF getPrivilegeType();
  public gov.geoplatform.uasdm.bus.PrivilegeTypeQuery.AllPrivilegeTypeQueryIF getPrivilegeType(String alias);
  public gov.geoplatform.uasdm.bus.PrivilegeTypeQuery.AllPrivilegeTypeQueryIF getPrivilegeType(String alias, String displayLabel);

    public com.runwaysdk.query.BasicCondition EQ(gov.geoplatform.uasdm.bus.Collection collection);

    public com.runwaysdk.query.BasicCondition NE(gov.geoplatform.uasdm.bus.Collection collection);


  public com.runwaysdk.query.Condition mission();
  public com.runwaysdk.query.Condition mission(gov.geoplatform.uasdm.bus.MissionQuery missionQuery);

  public com.runwaysdk.query.Condition mission(gov.geoplatform.uasdm.bus.MissionQuery missionQuery, gov.geoplatform.uasdm.bus.MissionHasCollectionQuery missionHasCollectionQuery);


  public com.runwaysdk.query.Condition SUBSELECT_mission();
  public com.runwaysdk.query.Condition SUBSELECT_mission(gov.geoplatform.uasdm.bus.MissionQuery missionQuery);

  public com.runwaysdk.query.Condition SUBSELECT_mission(gov.geoplatform.uasdm.bus.MissionQuery missionQuery, gov.geoplatform.uasdm.bus.MissionHasCollectionQuery missionHasCollectionQuery);


  public com.runwaysdk.query.Condition NOT_IN_mission();
  public com.runwaysdk.query.Condition NOT_IN_mission(gov.geoplatform.uasdm.bus.MissionQuery missionQuery);

  public com.runwaysdk.query.Condition NOT_IN_mission(gov.geoplatform.uasdm.bus.MissionQuery missionQuery, gov.geoplatform.uasdm.bus.MissionHasCollectionQuery missionHasCollectionQuery);


  public com.runwaysdk.query.Condition SUBSELECT_NOT_IN_mission();
  public com.runwaysdk.query.Condition SUBSELECT_NOT_IN_mission(gov.geoplatform.uasdm.bus.MissionQuery missionQuery);

  public com.runwaysdk.query.Condition SUBSELECT_NOT_IN_mission(gov.geoplatform.uasdm.bus.MissionQuery missionQuery, gov.geoplatform.uasdm.bus.MissionHasCollectionQuery missionHasCollectionQuery);

  }

/**
 * Implements type safe query methods.
 * This type is used when a join is performed on this class as a reference.
 **/
  public static class CollectionQueryReference extends gov.geoplatform.uasdm.bus.UasComponentQuery.UasComponentQueryReference
 implements CollectionQueryReferenceIF

  {

  public CollectionQueryReference(com.runwaysdk.dataaccess.MdAttributeRefDAOIF mdAttributeIF, String attributeNamespace, String definingTableName, String definingTableAlias, com.runwaysdk.dataaccess.MdBusinessDAOIF referenceMdBusinessIF, String referenceTableAlias, com.runwaysdk.query.ComponentQuery rootQuery, java.util.Set<com.runwaysdk.query.Join> tableJoinSet, String alias, String displayLabel)
  {
    super(mdAttributeIF, attributeNamespace, definingTableName, definingTableAlias, referenceMdBusinessIF, referenceTableAlias, rootQuery, tableJoinSet, alias, displayLabel);

  }


    public com.runwaysdk.query.BasicCondition EQ(gov.geoplatform.uasdm.bus.Collection collection)
    {
      if(collection == null) return this.EQ((java.lang.String)null);
      return this.EQ(collection.getOid());
    }

    public com.runwaysdk.query.BasicCondition NE(gov.geoplatform.uasdm.bus.Collection collection)
    {
      if(collection == null) return this.NE((java.lang.String)null);
      return this.NE(collection.getOid());
    }

  public com.runwaysdk.query.SelectableInteger getImageHeight()
  {
    return getImageHeight(null);

  }
 
  public com.runwaysdk.query.SelectableInteger getImageHeight(String alias)
  {
    return (com.runwaysdk.query.SelectableInteger)this.get(gov.geoplatform.uasdm.bus.Collection.IMAGEHEIGHT, alias, null);

  }
 
  public com.runwaysdk.query.SelectableInteger getImageHeight(String alias, String displayLabel)
  {
    return (com.runwaysdk.query.SelectableInteger)this.get(gov.geoplatform.uasdm.bus.Collection.IMAGEHEIGHT, alias, displayLabel);

  }
  public com.runwaysdk.query.SelectableInteger getImageWidth()
  {
    return getImageWidth(null);

  }
 
  public com.runwaysdk.query.SelectableInteger getImageWidth(String alias)
  {
    return (com.runwaysdk.query.SelectableInteger)this.get(gov.geoplatform.uasdm.bus.Collection.IMAGEWIDTH, alias, null);

  }
 
  public com.runwaysdk.query.SelectableInteger getImageWidth(String alias, String displayLabel)
  {
    return (com.runwaysdk.query.SelectableInteger)this.get(gov.geoplatform.uasdm.bus.Collection.IMAGEWIDTH, alias, displayLabel);

  }
  public com.runwaysdk.query.SelectableBoolean getMetadataUploaded()
  {
    return getMetadataUploaded(null);

  }
 
  public com.runwaysdk.query.SelectableBoolean getMetadataUploaded(String alias)
  {
    return (com.runwaysdk.query.SelectableBoolean)this.get(gov.geoplatform.uasdm.bus.Collection.METADATAUPLOADED, alias, null);

  }
 
  public com.runwaysdk.query.SelectableBoolean getMetadataUploaded(String alias, String displayLabel)
  {
    return (com.runwaysdk.query.SelectableBoolean)this.get(gov.geoplatform.uasdm.bus.Collection.METADATAUPLOADED, alias, displayLabel);

  }
  public gov.geoplatform.uasdm.bus.PrivilegeTypeQuery.AllPrivilegeTypeQueryIF getPrivilegeType()
  {
    return getPrivilegeType(null);

  }
 
  public gov.geoplatform.uasdm.bus.PrivilegeTypeQuery.AllPrivilegeTypeQueryIF getPrivilegeType(String alias)
  {
    return (gov.geoplatform.uasdm.bus.PrivilegeTypeQuery.AllPrivilegeTypeQueryIF)this.get(gov.geoplatform.uasdm.bus.Collection.PRIVILEGETYPE, alias, null);

  }
 
  public gov.geoplatform.uasdm.bus.PrivilegeTypeQuery.AllPrivilegeTypeQueryIF getPrivilegeType(String alias, String displayLabel)
  {
    return (gov.geoplatform.uasdm.bus.PrivilegeTypeQuery.AllPrivilegeTypeQueryIF)this.get(gov.geoplatform.uasdm.bus.Collection.PRIVILEGETYPE, alias, displayLabel);

  }

  public com.runwaysdk.query.Condition mission()
  {
    com.runwaysdk.query.QueryFactory queryFactory = this.getQueryFactory();
    com.runwaysdk.business.RelationshipQuery relationshipQuery = queryFactory.relationshipQuery(gov.geoplatform.uasdm.bus.MissionHasCollection.CLASS);

    return this.isChildIn(relationshipQuery);
  }


  public com.runwaysdk.query.Condition SUBSELECT_mission()
  {
    com.runwaysdk.query.QueryFactory queryFactory = this.getQueryFactory();
    com.runwaysdk.business.RelationshipQuery relationshipQuery = queryFactory.relationshipQuery(gov.geoplatform.uasdm.bus.MissionHasCollection.CLASS);

    return this.isChildIn_SUBSELECT(relationshipQuery);
  }

  public com.runwaysdk.query.Condition mission(gov.geoplatform.uasdm.bus.MissionHasCollectionQuery missionHasCollectionQuery)
  {
    return this.isChildIn(missionHasCollectionQuery);
  }

  public com.runwaysdk.query.Condition SUBSELECT_mission(gov.geoplatform.uasdm.bus.MissionHasCollectionQuery missionHasCollectionQuery)
  {
    return this.isChildIn_SUBSELECT(missionHasCollectionQuery);
  }

  public com.runwaysdk.query.Condition mission(gov.geoplatform.uasdm.bus.MissionQuery missionQuery)
  {
    com.runwaysdk.query.QueryFactory queryFactory = this.getQueryFactory();
    com.runwaysdk.business.RelationshipQuery relationshipQuery = queryFactory.relationshipQuery(gov.geoplatform.uasdm.bus.MissionHasCollection.CLASS);
    relationshipQuery.AND(relationshipQuery.hasParent(missionQuery));

    return this.isChildIn(relationshipQuery);
  }

  public com.runwaysdk.query.Condition SUBSELECT_mission(gov.geoplatform.uasdm.bus.MissionQuery missionQuery)
  {
    com.runwaysdk.query.QueryFactory queryFactory = this.getQueryFactory();
    com.runwaysdk.business.RelationshipQuery relationshipQuery = queryFactory.relationshipQuery(gov.geoplatform.uasdm.bus.MissionHasCollection.CLASS);
    relationshipQuery.AND(relationshipQuery.hasParent(missionQuery));

    return this.isChildIn_SUBSELECT(relationshipQuery);
  }

  public com.runwaysdk.query.Condition mission(gov.geoplatform.uasdm.bus.MissionQuery missionQuery, gov.geoplatform.uasdm.bus.MissionHasCollectionQuery missionHasCollectionQuery)
  {
    missionHasCollectionQuery.AND(missionHasCollectionQuery.hasParent(missionQuery));
    return this.isChildIn(missionHasCollectionQuery);
  }

  public com.runwaysdk.query.Condition SUBSELECT_mission(gov.geoplatform.uasdm.bus.MissionQuery missionQuery, gov.geoplatform.uasdm.bus.MissionHasCollectionQuery missionHasCollectionQuery)
  {
    missionHasCollectionQuery.AND(missionHasCollectionQuery.hasParent(missionQuery));
    return this.isChildIn_SUBSELECT(missionHasCollectionQuery);
  }


  public com.runwaysdk.query.Condition NOT_IN_mission()
  {
    com.runwaysdk.query.QueryFactory queryFactory = this.getQueryFactory();
    com.runwaysdk.business.RelationshipQuery relationshipQuery = queryFactory.relationshipQuery(gov.geoplatform.uasdm.bus.MissionHasCollection.CLASS);

    return this.isNotChildIn(relationshipQuery);
  }


  public com.runwaysdk.query.Condition SUBSELECT_NOT_IN_mission()
  {
    com.runwaysdk.query.QueryFactory queryFactory = this.getQueryFactory();
    com.runwaysdk.business.RelationshipQuery relationshipQuery = queryFactory.relationshipQuery(gov.geoplatform.uasdm.bus.MissionHasCollection.CLASS);

    return this.isNotChildIn_SUBSELECT(relationshipQuery);
  }

  public com.runwaysdk.query.Condition NOT_IN_mission(gov.geoplatform.uasdm.bus.MissionHasCollectionQuery missionHasCollectionQuery)
  {
    return this.isNotChildIn(missionHasCollectionQuery);
  }

  public com.runwaysdk.query.Condition SUBSELECT_NOT_IN_mission(gov.geoplatform.uasdm.bus.MissionHasCollectionQuery missionHasCollectionQuery)
  {
    return this.isNotChildIn_SUBSELECT(missionHasCollectionQuery);
  }

  public com.runwaysdk.query.Condition NOT_IN_mission(gov.geoplatform.uasdm.bus.MissionQuery missionQuery)
  {
    com.runwaysdk.query.QueryFactory queryFactory = this.getQueryFactory();
    com.runwaysdk.business.RelationshipQuery relationshipQuery = queryFactory.relationshipQuery(gov.geoplatform.uasdm.bus.MissionHasCollection.CLASS);
    relationshipQuery.AND(relationshipQuery.hasParent(missionQuery));

    return this.isNotChildIn(relationshipQuery);
  }

  public com.runwaysdk.query.Condition SUBSELECT_NOT_IN_mission(gov.geoplatform.uasdm.bus.MissionQuery missionQuery)
  {
    com.runwaysdk.query.QueryFactory queryFactory = this.getQueryFactory();
    com.runwaysdk.business.RelationshipQuery relationshipQuery = queryFactory.relationshipQuery(gov.geoplatform.uasdm.bus.MissionHasCollection.CLASS);
    relationshipQuery.AND(relationshipQuery.hasParent(missionQuery));

    return this.isNotChildIn_SUBSELECT(relationshipQuery);
  }

  public com.runwaysdk.query.Condition NOT_IN_mission(gov.geoplatform.uasdm.bus.MissionQuery missionQuery, gov.geoplatform.uasdm.bus.MissionHasCollectionQuery missionHasCollectionQuery)
  {
    missionHasCollectionQuery.AND(missionHasCollectionQuery.hasParent(missionQuery));
    return this.isNotChildIn(missionHasCollectionQuery);
  }

  public com.runwaysdk.query.Condition SUBSELECT_NOT_IN_mission(gov.geoplatform.uasdm.bus.MissionQuery missionQuery, gov.geoplatform.uasdm.bus.MissionHasCollectionQuery missionHasCollectionQuery)
  {
    missionHasCollectionQuery.AND(missionHasCollectionQuery.hasParent(missionQuery));
    return this.isNotChildIn_SUBSELECT(missionHasCollectionQuery);
  }

  protected com.runwaysdk.query.AttributeEnumeration enumerationFactory( com.runwaysdk.dataaccess.MdAttributeEnumerationDAOIF mdAttributeIF, String attributeNamespace, String definingTableName, String definingTableAlias,  String mdEnumerationTableName, com.runwaysdk.dataaccess.MdBusinessDAOIF masterListMdBusinessIF, String masterListTalbeAlias, com.runwaysdk.query.ComponentQuery rootQuery, java.util.Set<com.runwaysdk.query.Join> tableJoinSet, String userDefinedAlias, String userDefinedDisplayLabel)
  {
    String name = mdAttributeIF.definesAttribute();
    
    if (name.equals(gov.geoplatform.uasdm.bus.Collection.PRIVILEGETYPE)) 
    {
       return new gov.geoplatform.uasdm.bus.PrivilegeTypeQuery.AllPrivilegeTypeQuery((com.runwaysdk.dataaccess.MdAttributeEnumerationDAOIF)mdAttributeIF,  attributeNamespace, definingTableName, definingTableAlias, mdEnumerationTableName, masterListMdBusinessIF, masterListTalbeAlias, rootQuery, tableJoinSet, userDefinedAlias, userDefinedDisplayLabel);
    }
    else 
    {
      return super.enumerationFactory(mdAttributeIF, attributeNamespace, definingTableName, definingTableAlias, mdEnumerationTableName, masterListMdBusinessIF, masterListTalbeAlias, rootQuery, tableJoinSet, userDefinedAlias, userDefinedDisplayLabel);
    }
  }

  }

/**
 * Interface that masks all type unsafe query methods and defines all type safe methods.
 * This type is used when a join is performed on this class as a reference.
 **/
  public interface CollectionQueryMultiReferenceIF extends gov.geoplatform.uasdm.bus.UasComponentQuery.UasComponentQueryMultiReferenceIF
  {

    public com.runwaysdk.query.SelectableInteger getImageHeight();
    public com.runwaysdk.query.SelectableInteger getImageHeight(String alias);
    public com.runwaysdk.query.SelectableInteger getImageHeight(String alias, String displayLabel);
    public com.runwaysdk.query.SelectableInteger getImageWidth();
    public com.runwaysdk.query.SelectableInteger getImageWidth(String alias);
    public com.runwaysdk.query.SelectableInteger getImageWidth(String alias, String displayLabel);
    public com.runwaysdk.query.SelectableBoolean getMetadataUploaded();
    public com.runwaysdk.query.SelectableBoolean getMetadataUploaded(String alias);
    public com.runwaysdk.query.SelectableBoolean getMetadataUploaded(String alias, String displayLabel);
  public gov.geoplatform.uasdm.bus.PrivilegeTypeQuery.AllPrivilegeTypeQueryIF getPrivilegeType();
  public gov.geoplatform.uasdm.bus.PrivilegeTypeQuery.AllPrivilegeTypeQueryIF getPrivilegeType(String alias);
  public gov.geoplatform.uasdm.bus.PrivilegeTypeQuery.AllPrivilegeTypeQueryIF getPrivilegeType(String alias, String displayLabel);

    public com.runwaysdk.query.Condition containsAny(gov.geoplatform.uasdm.bus.Collection ... collection);
    public com.runwaysdk.query.Condition notContainsAny(gov.geoplatform.uasdm.bus.Collection ... collection);
    public com.runwaysdk.query.Condition containsAll(gov.geoplatform.uasdm.bus.Collection ... collection);
    public com.runwaysdk.query.Condition notContainsAll(gov.geoplatform.uasdm.bus.Collection ... collection);
    public com.runwaysdk.query.Condition containsExactly(gov.geoplatform.uasdm.bus.Collection ... collection);
  }

/**
 * Implements type safe query methods.
 * This type is used when a join is performed on this class as a reference.
 **/
  public static class CollectionQueryMultiReference extends gov.geoplatform.uasdm.bus.UasComponentQuery.UasComponentQueryMultiReference
 implements CollectionQueryMultiReferenceIF

  {

  public CollectionQueryMultiReference(com.runwaysdk.dataaccess.MdAttributeMultiReferenceDAOIF mdAttributeIF, String attributeNamespace, String definingTableName, String definingTableAlias, String mdMultiReferenceTableName, com.runwaysdk.dataaccess.MdBusinessDAOIF referenceMdBusinessIF, String referenceTableAlias, com.runwaysdk.query.ComponentQuery rootQuery, java.util.Set<com.runwaysdk.query.Join> tableJoinSet, String alias, String displayLabel)
  {
    super(mdAttributeIF, attributeNamespace, definingTableName, definingTableAlias, mdMultiReferenceTableName, referenceMdBusinessIF, referenceTableAlias, rootQuery, tableJoinSet, alias, displayLabel);

  }



    public com.runwaysdk.query.Condition containsAny(gov.geoplatform.uasdm.bus.Collection ... collection)  {

      String[] itemIdArray = new String[collection.length]; 

      for (int i=0; i<collection.length; i++)
      {
        itemIdArray[i] = collection[i].getOid();
      }

      return this.containsAny(itemIdArray);
  }

    public com.runwaysdk.query.Condition notContainsAny(gov.geoplatform.uasdm.bus.Collection ... collection)  {

      String[] itemIdArray = new String[collection.length]; 

      for (int i=0; i<collection.length; i++)
      {
        itemIdArray[i] = collection[i].getOid();
      }

      return this.notContainsAny(itemIdArray);
  }

    public com.runwaysdk.query.Condition containsAll(gov.geoplatform.uasdm.bus.Collection ... collection)  {

      String[] itemIdArray = new String[collection.length]; 

      for (int i=0; i<collection.length; i++)
      {
        itemIdArray[i] = collection[i].getOid();
      }

      return this.containsAll(itemIdArray);
  }

    public com.runwaysdk.query.Condition notContainsAll(gov.geoplatform.uasdm.bus.Collection ... collection)  {

      String[] itemIdArray = new String[collection.length]; 

      for (int i=0; i<collection.length; i++)
      {
        itemIdArray[i] = collection[i].getOid();
      }

      return this.notContainsAll(itemIdArray);
  }

    public com.runwaysdk.query.Condition containsExactly(gov.geoplatform.uasdm.bus.Collection ... collection)  {

      String[] itemIdArray = new String[collection.length]; 

      for (int i=0; i<collection.length; i++)
      {
        itemIdArray[i] = collection[i].getOid();
      }

      return this.containsExactly(itemIdArray);
  }
  public com.runwaysdk.query.SelectableInteger getImageHeight()
  {
    return getImageHeight(null);

  }
 
  public com.runwaysdk.query.SelectableInteger getImageHeight(String alias)
  {
    return (com.runwaysdk.query.SelectableInteger)this.get(gov.geoplatform.uasdm.bus.Collection.IMAGEHEIGHT, alias, null);

  }
 
  public com.runwaysdk.query.SelectableInteger getImageHeight(String alias, String displayLabel)
  {
    return (com.runwaysdk.query.SelectableInteger)this.get(gov.geoplatform.uasdm.bus.Collection.IMAGEHEIGHT, alias, displayLabel);

  }
  public com.runwaysdk.query.SelectableInteger getImageWidth()
  {
    return getImageWidth(null);

  }
 
  public com.runwaysdk.query.SelectableInteger getImageWidth(String alias)
  {
    return (com.runwaysdk.query.SelectableInteger)this.get(gov.geoplatform.uasdm.bus.Collection.IMAGEWIDTH, alias, null);

  }
 
  public com.runwaysdk.query.SelectableInteger getImageWidth(String alias, String displayLabel)
  {
    return (com.runwaysdk.query.SelectableInteger)this.get(gov.geoplatform.uasdm.bus.Collection.IMAGEWIDTH, alias, displayLabel);

  }
  public com.runwaysdk.query.SelectableBoolean getMetadataUploaded()
  {
    return getMetadataUploaded(null);

  }
 
  public com.runwaysdk.query.SelectableBoolean getMetadataUploaded(String alias)
  {
    return (com.runwaysdk.query.SelectableBoolean)this.get(gov.geoplatform.uasdm.bus.Collection.METADATAUPLOADED, alias, null);

  }
 
  public com.runwaysdk.query.SelectableBoolean getMetadataUploaded(String alias, String displayLabel)
  {
    return (com.runwaysdk.query.SelectableBoolean)this.get(gov.geoplatform.uasdm.bus.Collection.METADATAUPLOADED, alias, displayLabel);

  }
  public gov.geoplatform.uasdm.bus.PrivilegeTypeQuery.AllPrivilegeTypeQueryIF getPrivilegeType()
  {
    return getPrivilegeType(null);

  }
 
  public gov.geoplatform.uasdm.bus.PrivilegeTypeQuery.AllPrivilegeTypeQueryIF getPrivilegeType(String alias)
  {
    return (gov.geoplatform.uasdm.bus.PrivilegeTypeQuery.AllPrivilegeTypeQueryIF)this.get(gov.geoplatform.uasdm.bus.Collection.PRIVILEGETYPE, alias, null);

  }
 
  public gov.geoplatform.uasdm.bus.PrivilegeTypeQuery.AllPrivilegeTypeQueryIF getPrivilegeType(String alias, String displayLabel)
  {
    return (gov.geoplatform.uasdm.bus.PrivilegeTypeQuery.AllPrivilegeTypeQueryIF)this.get(gov.geoplatform.uasdm.bus.Collection.PRIVILEGETYPE, alias, displayLabel);

  }
  protected com.runwaysdk.query.AttributeEnumeration enumerationFactory( com.runwaysdk.dataaccess.MdAttributeEnumerationDAOIF mdAttributeIF, String attributeNamespace, String definingTableName, String definingTableAlias,  String mdEnumerationTableName, com.runwaysdk.dataaccess.MdBusinessDAOIF masterListMdBusinessIF, String masterListTalbeAlias, com.runwaysdk.query.ComponentQuery rootQuery, java.util.Set<com.runwaysdk.query.Join> tableJoinSet, String userDefinedAlias, String userDefinedDisplayLabel)
  {
    String name = mdAttributeIF.definesAttribute();
    
    if (name.equals(gov.geoplatform.uasdm.bus.Collection.PRIVILEGETYPE)) 
    {
       return new gov.geoplatform.uasdm.bus.PrivilegeTypeQuery.AllPrivilegeTypeQuery((com.runwaysdk.dataaccess.MdAttributeEnumerationDAOIF)mdAttributeIF,  attributeNamespace, definingTableName, definingTableAlias, mdEnumerationTableName, masterListMdBusinessIF, masterListTalbeAlias, rootQuery, tableJoinSet, userDefinedAlias, userDefinedDisplayLabel);
    }
    else 
    {
      return super.enumerationFactory(mdAttributeIF, attributeNamespace, definingTableName, definingTableAlias, mdEnumerationTableName, masterListMdBusinessIF, masterListTalbeAlias, rootQuery, tableJoinSet, userDefinedAlias, userDefinedDisplayLabel);
    }
  }

  }
}
