package gov.geoplatform.uasdm.bus;

@com.runwaysdk.business.ClassSignature(hash = 1310429954)
/**
 * This class is generated automatically.
 * DO NOT MAKE CHANGES TO IT - THEY WILL BE OVERWRITTEN
 * Custom business logic should be added to DocumentGeneratedProduct.java
 *
 * @author Autogenerated by RunwaySDK
 */
public class DocumentGeneratedProductQueryDTO extends com.runwaysdk.business.RelationshipQueryDTO
{
private static final long serialVersionUID = 1310429954;

  protected DocumentGeneratedProductQueryDTO(String type)
  {
    super(type);
  }

@SuppressWarnings("unchecked")
public java.util.List<? extends gov.geoplatform.uasdm.bus.DocumentGeneratedProductDTO> getResultSet()
{
  return (java.util.List<? extends gov.geoplatform.uasdm.bus.DocumentGeneratedProductDTO>)super.getResultSet();
}
}
