package gov.geoplatform.uasdm.bus;

@com.runwaysdk.business.ClassSignature(hash = -2129289808)
/**
 * This class is generated automatically.
 * DO NOT MAKE CHANGES TO IT - THEY WILL BE OVERWRITTEN
 * Custom business logic should be added to DuplicateSiteException.java
 *
 * @author Autogenerated by RunwaySDK
 */
public abstract class DuplicateSiteExceptionBase extends com.runwaysdk.business.SmartException
{
  public final static String CLASS = "gov.geoplatform.uasdm.bus.DuplicateSiteException";
  public static java.lang.String FOLDERNAME = "folderName";
  public static java.lang.String OID = "oid";
  public static final long serialVersionUID = -2129289808;
  
  public DuplicateSiteExceptionBase()
  {
    super();
  }
  
  public DuplicateSiteExceptionBase(java.lang.String developerMessage)
  {
    super(developerMessage);
  }
  
  public DuplicateSiteExceptionBase(java.lang.String developerMessage, java.lang.Throwable cause)
  {
    super(developerMessage, cause);
  }
  
  public DuplicateSiteExceptionBase(java.lang.Throwable cause)
  {
    super(cause);
  }
  
  public String getFolderName()
  {
    return getValue(FOLDERNAME);
  }
  
  public void validateFolderName()
  {
    this.validateAttribute(FOLDERNAME);
  }
  
  public static com.runwaysdk.dataaccess.MdAttributeTextDAOIF getFolderNameMd()
  {
    com.runwaysdk.dataaccess.MdClassDAOIF mdClassIF = com.runwaysdk.dataaccess.metadata.MdClassDAO.getMdClassDAO(gov.geoplatform.uasdm.bus.DuplicateSiteException.CLASS);
    return (com.runwaysdk.dataaccess.MdAttributeTextDAOIF)mdClassIF.definesAttribute(FOLDERNAME);
  }
  
  public void setFolderName(String value)
  {
    if(value == null)
    {
      setValue(FOLDERNAME, "");
    }
    else
    {
      setValue(FOLDERNAME, value);
    }
  }
  
  public String getOid()
  {
    return getValue(OID);
  }
  
  public void validateOid()
  {
    this.validateAttribute(OID);
  }
  
  public static com.runwaysdk.dataaccess.MdAttributeUUIDDAOIF getOidMd()
  {
    com.runwaysdk.dataaccess.MdClassDAOIF mdClassIF = com.runwaysdk.dataaccess.metadata.MdClassDAO.getMdClassDAO(gov.geoplatform.uasdm.bus.DuplicateSiteException.CLASS);
    return (com.runwaysdk.dataaccess.MdAttributeUUIDDAOIF)mdClassIF.definesAttribute(OID);
  }
  
  protected String getDeclaredType()
  {
    return CLASS;
  }
  
  public java.lang.String localize(java.util.Locale locale)
  {
    java.lang.String message = super.localize(locale);
    message = replace(message, "{folderName}", this.getFolderName());
    message = replace(message, "{oid}", this.getOid());
    return message;
  }
  
}
