package gov.geoplatform.uasdm.bus;

@com.runwaysdk.business.ClassSignature(hash = 876407578)
/**
 * This class is generated automatically.
 * DO NOT MAKE CHANGES TO IT - THEY WILL BE OVERWRITTEN
 * Custom business logic should be added to InvalidUasComponentNameException.java
 *
 * @author Autogenerated by RunwaySDK
 */
public abstract class InvalidUasComponentNameExceptionBase extends com.runwaysdk.business.SmartException
{
  public final static String CLASS = "gov.geoplatform.uasdm.bus.InvalidUasComponentNameException";
  public static java.lang.String ATTRIBUTENAME = "attributeName";
  public static java.lang.String OID = "oid";
  private static final long serialVersionUID = 876407578;
  
  public InvalidUasComponentNameExceptionBase()
  {
    super();
  }
  
  public InvalidUasComponentNameExceptionBase(java.lang.String developerMessage)
  {
    super(developerMessage);
  }
  
  public InvalidUasComponentNameExceptionBase(java.lang.String developerMessage, java.lang.Throwable cause)
  {
    super(developerMessage, cause);
  }
  
  public InvalidUasComponentNameExceptionBase(java.lang.Throwable cause)
  {
    super(cause);
  }
  
  public String getAttributeName()
  {
    return getValue(ATTRIBUTENAME);
  }
  
  public void validateAttributeName()
  {
    this.validateAttribute(ATTRIBUTENAME);
  }
  
  public static com.runwaysdk.dataaccess.MdAttributeTextDAOIF getAttributeNameMd()
  {
    com.runwaysdk.dataaccess.MdClassDAOIF mdClassIF = com.runwaysdk.dataaccess.metadata.MdClassDAO.getMdClassDAO(gov.geoplatform.uasdm.bus.InvalidUasComponentNameException.CLASS);
    return (com.runwaysdk.dataaccess.MdAttributeTextDAOIF)mdClassIF.definesAttribute(ATTRIBUTENAME);
  }
  
  public void setAttributeName(String value)
  {
    if(value == null)
    {
      setValue(ATTRIBUTENAME, "");
    }
    else
    {
      setValue(ATTRIBUTENAME, value);
    }
  }
  
  public String getOid()
  {
    return getValue(OID);
  }
  
  public void validateOid()
  {
    this.validateAttribute(OID);
  }
  
  public static com.runwaysdk.dataaccess.MdAttributeUUIDDAOIF getOidMd()
  {
    com.runwaysdk.dataaccess.MdClassDAOIF mdClassIF = com.runwaysdk.dataaccess.metadata.MdClassDAO.getMdClassDAO(gov.geoplatform.uasdm.bus.InvalidUasComponentNameException.CLASS);
    return (com.runwaysdk.dataaccess.MdAttributeUUIDDAOIF)mdClassIF.definesAttribute(OID);
  }
  
  protected String getDeclaredType()
  {
    return CLASS;
  }
  
  public java.lang.String localize(java.util.Locale locale)
  {
    java.lang.String message = super.localize(locale);
    message = replace(message, "{attributeName}", this.getAttributeName());
    message = replace(message, "{oid}", this.getOid());
    return message;
  }
  
}
