package gov.geoplatform.uasdm.bus;

@com.runwaysdk.business.ClassSignature(hash = 1419697395)
/**
 * This class is generated automatically.
 * DO NOT MAKE CHANGES TO IT - THEY WILL BE OVERWRITTEN
 * Custom business logic should be added to Mission.java
 *
 * @author Autogenerated by RunwaySDK
 */
public abstract class MissionBase extends gov.geoplatform.uasdm.bus.UasComponent
{
  public final static String CLASS = "gov.geoplatform.uasdm.bus.Mission";
  public static java.lang.String METADATAUPLOADED = "metadataUploaded";
  private static final long serialVersionUID = 1419697395;
  
  public MissionBase()
  {
    super();
  }
  
  public Boolean getMetadataUploaded()
  {
    return com.runwaysdk.constants.MdAttributeBooleanUtil.getTypeSafeValue(getValue(METADATAUPLOADED));
  }
  
  public void validateMetadataUploaded()
  {
    this.validateAttribute(METADATAUPLOADED);
  }
  
  public static com.runwaysdk.dataaccess.MdAttributeBooleanDAOIF getMetadataUploadedMd()
  {
    com.runwaysdk.dataaccess.MdClassDAOIF mdClassIF = com.runwaysdk.dataaccess.metadata.MdClassDAO.getMdClassDAO(gov.geoplatform.uasdm.bus.Mission.CLASS);
    return (com.runwaysdk.dataaccess.MdAttributeBooleanDAOIF)mdClassIF.definesAttribute(METADATAUPLOADED);
  }
  
  public void setMetadataUploaded(Boolean value)
  {
    if(value == null)
    {
      setValue(METADATAUPLOADED, "");
    }
    else
    {
      setValue(METADATAUPLOADED, java.lang.Boolean.toString(value));
    }
  }
  
  protected String getDeclaredType()
  {
    return CLASS;
  }
  
  public static MissionQuery getAllInstances(String sortAttribute, Boolean ascending, Integer pageSize, Integer pageNumber)
  {
    MissionQuery query = new MissionQuery(new com.runwaysdk.query.QueryFactory());
    com.runwaysdk.business.Entity.getAllInstances(query, sortAttribute, ascending, pageSize, pageNumber);
    return query;
  }
  
  public gov.geoplatform.uasdm.bus.MissionHasCollection addCollections(gov.geoplatform.uasdm.bus.Collection collection)
  {
    return (gov.geoplatform.uasdm.bus.MissionHasCollection) addChild(collection, gov.geoplatform.uasdm.bus.MissionHasCollection.CLASS);
  }
  
  public void removeCollections(gov.geoplatform.uasdm.bus.Collection collection)
  {
    removeAllChildren(collection, gov.geoplatform.uasdm.bus.MissionHasCollection.CLASS);
  }
  
  @SuppressWarnings("unchecked")
  public com.runwaysdk.query.OIterator<? extends gov.geoplatform.uasdm.bus.Collection> getAllCollections()
  {
    return (com.runwaysdk.query.OIterator<? extends gov.geoplatform.uasdm.bus.Collection>) getChildren(gov.geoplatform.uasdm.bus.MissionHasCollection.CLASS);
  }
  
  @SuppressWarnings("unchecked")
  public com.runwaysdk.query.OIterator<? extends gov.geoplatform.uasdm.bus.MissionHasCollection> getAllCollectionsRel()
  {
    return (com.runwaysdk.query.OIterator<? extends gov.geoplatform.uasdm.bus.MissionHasCollection>) getChildRelationships(gov.geoplatform.uasdm.bus.MissionHasCollection.CLASS);
  }
  
  @SuppressWarnings("unchecked")
  public gov.geoplatform.uasdm.bus.MissionHasCollection getCollectionsRel(gov.geoplatform.uasdm.bus.Collection collection)
  {
    com.runwaysdk.query.OIterator<? extends gov.geoplatform.uasdm.bus.MissionHasCollection> iterator = (com.runwaysdk.query.OIterator<? extends gov.geoplatform.uasdm.bus.MissionHasCollection>) getRelationshipsWithChild(collection, gov.geoplatform.uasdm.bus.MissionHasCollection.CLASS);
    try
    {
      if (iterator.hasNext())
      {
        return iterator.next();
      }
      else
      {
        return null;
      }
    }
    finally
    {
      iterator.close();
    }
  }
  
  public gov.geoplatform.uasdm.bus.ProjectHasMission addProject(gov.geoplatform.uasdm.bus.Project project)
  {
    return (gov.geoplatform.uasdm.bus.ProjectHasMission) addParent(project, gov.geoplatform.uasdm.bus.ProjectHasMission.CLASS);
  }
  
  public void removeProject(gov.geoplatform.uasdm.bus.Project project)
  {
    removeAllParents(project, gov.geoplatform.uasdm.bus.ProjectHasMission.CLASS);
  }
  
  @SuppressWarnings("unchecked")
  public com.runwaysdk.query.OIterator<? extends gov.geoplatform.uasdm.bus.Project> getAllProject()
  {
    return (com.runwaysdk.query.OIterator<? extends gov.geoplatform.uasdm.bus.Project>) getParents(gov.geoplatform.uasdm.bus.ProjectHasMission.CLASS);
  }
  
  @SuppressWarnings("unchecked")
  public com.runwaysdk.query.OIterator<? extends gov.geoplatform.uasdm.bus.ProjectHasMission> getAllProjectRel()
  {
    return (com.runwaysdk.query.OIterator<? extends gov.geoplatform.uasdm.bus.ProjectHasMission>) getParentRelationships(gov.geoplatform.uasdm.bus.ProjectHasMission.CLASS);
  }
  
  @SuppressWarnings("unchecked")
  public gov.geoplatform.uasdm.bus.ProjectHasMission getProjectRel(gov.geoplatform.uasdm.bus.Project project)
  {
    com.runwaysdk.query.OIterator<? extends gov.geoplatform.uasdm.bus.ProjectHasMission> iterator = (com.runwaysdk.query.OIterator<? extends gov.geoplatform.uasdm.bus.ProjectHasMission>) getRelationshipsWithParent(project, gov.geoplatform.uasdm.bus.ProjectHasMission.CLASS);
    try
    {
      if (iterator.hasNext())
      {
        return iterator.next();
      }
      else
      {
        return null;
      }
    }
    finally
    {
      iterator.close();
    }
  }
  
  public static Mission get(String oid)
  {
    return (Mission) com.runwaysdk.business.Business.get(oid);
  }
  
  public static Mission getByKey(String key)
  {
    return (Mission) com.runwaysdk.business.Business.get(CLASS, key);
  }
  
  public static Mission lock(java.lang.String oid)
  {
    Mission _instance = Mission.get(oid);
    _instance.lock();
    
    return _instance;
  }
  
  public static Mission unlock(java.lang.String oid)
  {
    Mission _instance = Mission.get(oid);
    _instance.unlock();
    
    return _instance;
  }
  
  public String toString()
  {
    if (this.isNew())
    {
      return "New: "+ this.getClassDisplayLabel();
    }
    else
    {
      return super.toString();
    }
  }
}
