package gov.geoplatform.uasdm.bus;

@com.runwaysdk.business.ClassSignature(hash = 119354947)
/**
 * This class is generated automatically.
 * DO NOT MAKE CHANGES TO IT - THEY WILL BE OVERWRITTEN
 * Custom business logic should be added to MissingMetadataMessage.java
 *
 * @author Autogenerated by RunwaySDK
 */
public abstract class MissingMetadataMessageBase extends gov.geoplatform.uasdm.bus.AbstractMessage
{
  public final static String CLASS = "gov.geoplatform.uasdm.bus.MissingMetadataMessage";
  public static java.lang.String COMPONENT = "component";
  private static final long serialVersionUID = 119354947;
  
  public MissingMetadataMessageBase()
  {
    super();
  }
  
  public String getComponent()
  {
    return getValue(COMPONENT);
  }
  
  public void validateComponent()
  {
    this.validateAttribute(COMPONENT);
  }
  
  public static com.runwaysdk.dataaccess.MdAttributeUUIDDAOIF getComponentMd()
  {
    com.runwaysdk.dataaccess.MdClassDAOIF mdClassIF = com.runwaysdk.dataaccess.metadata.MdClassDAO.getMdClassDAO(gov.geoplatform.uasdm.bus.MissingMetadataMessage.CLASS);
    return (com.runwaysdk.dataaccess.MdAttributeUUIDDAOIF)mdClassIF.definesAttribute(COMPONENT);
  }
  
  public void setComponent(String value)
  {
    if(value == null)
    {
      setValue(COMPONENT, "");
    }
    else
    {
      setValue(COMPONENT, value);
    }
  }
  
  protected String getDeclaredType()
  {
    return CLASS;
  }
  
  public static MissingMetadataMessageQuery getAllInstances(String sortAttribute, Boolean ascending, Integer pageSize, Integer pageNumber)
  {
    MissingMetadataMessageQuery query = new MissingMetadataMessageQuery(new com.runwaysdk.query.QueryFactory());
    com.runwaysdk.business.Entity.getAllInstances(query, sortAttribute, ascending, pageSize, pageNumber);
    return query;
  }
  
  public static MissingMetadataMessage get(String oid)
  {
    return (MissingMetadataMessage) com.runwaysdk.business.Business.get(oid);
  }
  
  public static MissingMetadataMessage getByKey(String key)
  {
    return (MissingMetadataMessage) com.runwaysdk.business.Business.get(CLASS, key);
  }
  
  public static MissingMetadataMessage lock(java.lang.String oid)
  {
    MissingMetadataMessage _instance = MissingMetadataMessage.get(oid);
    _instance.lock();
    
    return _instance;
  }
  
  public static MissingMetadataMessage unlock(java.lang.String oid)
  {
    MissingMetadataMessage _instance = MissingMetadataMessage.get(oid);
    _instance.unlock();
    
    return _instance;
  }
  
  public String toString()
  {
    if (this.isNew())
    {
      return "New: "+ this.getClassDisplayLabel();
    }
    else
    {
      return super.toString();
    }
  }
}
