package gov.geoplatform.uasdm.bus;

@com.runwaysdk.business.ClassSignature(hash = -1073285830)
/**
 * This class is generated automatically.
 * DO NOT MAKE CHANGES TO IT - THEY WILL BE OVERWRITTEN
 * Custom business logic should be added to MissingMetadataMessage.java
 *
 * @author Autogenerated by RunwaySDK
 */
public  class MissingMetadataMessageQuery extends gov.geoplatform.uasdm.bus.AbstractMessageQuery

{

  public MissingMetadataMessageQuery(com.runwaysdk.query.QueryFactory componentQueryFactory)
  {
    super(componentQueryFactory);
    if (this.getComponentQuery() == null)
    {
      com.runwaysdk.business.BusinessQuery businessQuery = componentQueryFactory.businessQuery(this.getClassType());

       this.setBusinessQuery(businessQuery);
    }
  }

  public MissingMetadataMessageQuery(com.runwaysdk.query.ValueQuery valueQuery)
  {
    super(valueQuery);
    if (this.getComponentQuery() == null)
    {
      com.runwaysdk.business.BusinessQuery businessQuery = new com.runwaysdk.business.BusinessQuery(valueQuery, this.getClassType());

       this.setBusinessQuery(businessQuery);
    }
  }

  public String getClassType()
  {
    return gov.geoplatform.uasdm.bus.MissingMetadataMessage.CLASS;
  }
  public com.runwaysdk.query.SelectableUUID getComponent()
  {
    return getComponent(null);

  }
 
  public com.runwaysdk.query.SelectableUUID getComponent(String alias)
  {
    return (com.runwaysdk.query.SelectableUUID)this.getComponentQuery().get(gov.geoplatform.uasdm.bus.MissingMetadataMessage.COMPONENT, alias, null);

  }
 
  public com.runwaysdk.query.SelectableUUID getComponent(String alias, String displayLabel)
  {
    return (com.runwaysdk.query.SelectableUUID)this.getComponentQuery().get(gov.geoplatform.uasdm.bus.MissingMetadataMessage.COMPONENT, alias, displayLabel);

  }
  /**  
   * Returns an iterator of Business objects that match the query criteria specified
   * on this query object. 
   * @return iterator of Business objects that match the query criteria specified
   * on this query object.
   */
  public com.runwaysdk.query.OIterator<? extends MissingMetadataMessage> getIterator()
  {
    this.checkNotUsedInValueQuery();
    String sqlStmt;
    if (_limit != null && _skip != null)
    {
      sqlStmt = this.getComponentQuery().getSQL(_limit, _skip);
    }
    else
    {
      sqlStmt = this.getComponentQuery().getSQL();
    }
    java.util.Map<String, com.runwaysdk.query.ColumnInfo> columnInfoMap = this.getComponentQuery().getColumnInfoMap();

    java.sql.ResultSet results = com.runwaysdk.dataaccess.database.Database.query(sqlStmt);
    return new com.runwaysdk.business.BusinessIterator<MissingMetadataMessage>(this.getComponentQuery().getMdEntityIF(), columnInfoMap, results);
  }


/**
 * Interface that masks all type unsafe query methods and defines all type safe methods.
 * This type is used when a join is performed on this class as a reference.
 **/
  public interface MissingMetadataMessageQueryReferenceIF extends gov.geoplatform.uasdm.bus.AbstractMessageQuery.AbstractMessageQueryReferenceIF
  {

    public com.runwaysdk.query.SelectableUUID getComponent();
    public com.runwaysdk.query.SelectableUUID getComponent(String alias);
    public com.runwaysdk.query.SelectableUUID getComponent(String alias, String displayLabel);

    public com.runwaysdk.query.BasicCondition EQ(gov.geoplatform.uasdm.bus.MissingMetadataMessage missingMetadataMessage);

    public com.runwaysdk.query.BasicCondition NE(gov.geoplatform.uasdm.bus.MissingMetadataMessage missingMetadataMessage);

  }

/**
 * Implements type safe query methods.
 * This type is used when a join is performed on this class as a reference.
 **/
  public static class MissingMetadataMessageQueryReference extends gov.geoplatform.uasdm.bus.AbstractMessageQuery.AbstractMessageQueryReference
 implements MissingMetadataMessageQueryReferenceIF

  {

  public MissingMetadataMessageQueryReference(com.runwaysdk.dataaccess.MdAttributeRefDAOIF mdAttributeIF, String attributeNamespace, String definingTableName, String definingTableAlias, com.runwaysdk.dataaccess.MdBusinessDAOIF referenceMdBusinessIF, String referenceTableAlias, com.runwaysdk.query.ComponentQuery rootQuery, java.util.Set<com.runwaysdk.query.Join> tableJoinSet, String alias, String displayLabel)
  {
    super(mdAttributeIF, attributeNamespace, definingTableName, definingTableAlias, referenceMdBusinessIF, referenceTableAlias, rootQuery, tableJoinSet, alias, displayLabel);

  }


    public com.runwaysdk.query.BasicCondition EQ(gov.geoplatform.uasdm.bus.MissingMetadataMessage missingMetadataMessage)
    {
      if(missingMetadataMessage == null) return this.EQ((java.lang.String)null);
      return this.EQ(missingMetadataMessage.getOid());
    }

    public com.runwaysdk.query.BasicCondition NE(gov.geoplatform.uasdm.bus.MissingMetadataMessage missingMetadataMessage)
    {
      if(missingMetadataMessage == null) return this.NE((java.lang.String)null);
      return this.NE(missingMetadataMessage.getOid());
    }

  public com.runwaysdk.query.SelectableUUID getComponent()
  {
    return getComponent(null);

  }
 
  public com.runwaysdk.query.SelectableUUID getComponent(String alias)
  {
    return (com.runwaysdk.query.SelectableUUID)this.get(gov.geoplatform.uasdm.bus.MissingMetadataMessage.COMPONENT, alias, null);

  }
 
  public com.runwaysdk.query.SelectableUUID getComponent(String alias, String displayLabel)
  {
    return (com.runwaysdk.query.SelectableUUID)this.get(gov.geoplatform.uasdm.bus.MissingMetadataMessage.COMPONENT, alias, displayLabel);

  }
  }

/**
 * Interface that masks all type unsafe query methods and defines all type safe methods.
 * This type is used when a join is performed on this class as a reference.
 **/
  public interface MissingMetadataMessageQueryMultiReferenceIF extends gov.geoplatform.uasdm.bus.AbstractMessageQuery.AbstractMessageQueryMultiReferenceIF
  {

    public com.runwaysdk.query.SelectableUUID getComponent();
    public com.runwaysdk.query.SelectableUUID getComponent(String alias);
    public com.runwaysdk.query.SelectableUUID getComponent(String alias, String displayLabel);

    public com.runwaysdk.query.Condition containsAny(gov.geoplatform.uasdm.bus.MissingMetadataMessage ... missingMetadataMessage);
    public com.runwaysdk.query.Condition notContainsAny(gov.geoplatform.uasdm.bus.MissingMetadataMessage ... missingMetadataMessage);
    public com.runwaysdk.query.Condition containsAll(gov.geoplatform.uasdm.bus.MissingMetadataMessage ... missingMetadataMessage);
    public com.runwaysdk.query.Condition notContainsAll(gov.geoplatform.uasdm.bus.MissingMetadataMessage ... missingMetadataMessage);
    public com.runwaysdk.query.Condition containsExactly(gov.geoplatform.uasdm.bus.MissingMetadataMessage ... missingMetadataMessage);
  }

/**
 * Implements type safe query methods.
 * This type is used when a join is performed on this class as a reference.
 **/
  public static class MissingMetadataMessageQueryMultiReference extends gov.geoplatform.uasdm.bus.AbstractMessageQuery.AbstractMessageQueryMultiReference
 implements MissingMetadataMessageQueryMultiReferenceIF

  {

  public MissingMetadataMessageQueryMultiReference(com.runwaysdk.dataaccess.MdAttributeMultiReferenceDAOIF mdAttributeIF, String attributeNamespace, String definingTableName, String definingTableAlias, String mdMultiReferenceTableName, com.runwaysdk.dataaccess.MdBusinessDAOIF referenceMdBusinessIF, String referenceTableAlias, com.runwaysdk.query.ComponentQuery rootQuery, java.util.Set<com.runwaysdk.query.Join> tableJoinSet, String alias, String displayLabel)
  {
    super(mdAttributeIF, attributeNamespace, definingTableName, definingTableAlias, mdMultiReferenceTableName, referenceMdBusinessIF, referenceTableAlias, rootQuery, tableJoinSet, alias, displayLabel);

  }



    public com.runwaysdk.query.Condition containsAny(gov.geoplatform.uasdm.bus.MissingMetadataMessage ... missingMetadataMessage)  {

      String[] itemIdArray = new String[missingMetadataMessage.length]; 

      for (int i=0; i<missingMetadataMessage.length; i++)
      {
        itemIdArray[i] = missingMetadataMessage[i].getOid();
      }

      return this.containsAny(itemIdArray);
  }

    public com.runwaysdk.query.Condition notContainsAny(gov.geoplatform.uasdm.bus.MissingMetadataMessage ... missingMetadataMessage)  {

      String[] itemIdArray = new String[missingMetadataMessage.length]; 

      for (int i=0; i<missingMetadataMessage.length; i++)
      {
        itemIdArray[i] = missingMetadataMessage[i].getOid();
      }

      return this.notContainsAny(itemIdArray);
  }

    public com.runwaysdk.query.Condition containsAll(gov.geoplatform.uasdm.bus.MissingMetadataMessage ... missingMetadataMessage)  {

      String[] itemIdArray = new String[missingMetadataMessage.length]; 

      for (int i=0; i<missingMetadataMessage.length; i++)
      {
        itemIdArray[i] = missingMetadataMessage[i].getOid();
      }

      return this.containsAll(itemIdArray);
  }

    public com.runwaysdk.query.Condition notContainsAll(gov.geoplatform.uasdm.bus.MissingMetadataMessage ... missingMetadataMessage)  {

      String[] itemIdArray = new String[missingMetadataMessage.length]; 

      for (int i=0; i<missingMetadataMessage.length; i++)
      {
        itemIdArray[i] = missingMetadataMessage[i].getOid();
      }

      return this.notContainsAll(itemIdArray);
  }

    public com.runwaysdk.query.Condition containsExactly(gov.geoplatform.uasdm.bus.MissingMetadataMessage ... missingMetadataMessage)  {

      String[] itemIdArray = new String[missingMetadataMessage.length]; 

      for (int i=0; i<missingMetadataMessage.length; i++)
      {
        itemIdArray[i] = missingMetadataMessage[i].getOid();
      }

      return this.containsExactly(itemIdArray);
  }
  public com.runwaysdk.query.SelectableUUID getComponent()
  {
    return getComponent(null);

  }
 
  public com.runwaysdk.query.SelectableUUID getComponent(String alias)
  {
    return (com.runwaysdk.query.SelectableUUID)this.get(gov.geoplatform.uasdm.bus.MissingMetadataMessage.COMPONENT, alias, null);

  }
 
  public com.runwaysdk.query.SelectableUUID getComponent(String alias, String displayLabel)
  {
    return (com.runwaysdk.query.SelectableUUID)this.get(gov.geoplatform.uasdm.bus.MissingMetadataMessage.COMPONENT, alias, displayLabel);

  }
  }
}
