package gov.geoplatform.uasdm.bus;

@com.runwaysdk.business.ClassSignature(hash = 1498618192)
/**
 * This class is generated automatically.
 * DO NOT MAKE CHANGES TO IT - THEY WILL BE OVERWRITTEN
 * Custom business logic should be added to MissionHasCollection.java
 *
 * @author Autogenerated by RunwaySDK
 */
public abstract class MissionHasCollectionBase extends gov.geoplatform.uasdm.bus.ComponentHasComponent
{
  public final static String CLASS = "gov.geoplatform.uasdm.bus.MissionHasCollection";
  public static final long serialVersionUID = 1498618192;
  
  public MissionHasCollectionBase(String parentOid, String childOid)
  {
    super(parentOid, childOid);
  }
  
  protected String getDeclaredType()
  {
    return CLASS;
  }
  
  public static MissionHasCollectionQuery getAllInstances(String sortAttribute, Boolean ascending, Integer pageSize, Integer pageNumber)
  {
    MissionHasCollectionQuery query = new MissionHasCollectionQuery(new com.runwaysdk.query.QueryFactory());
    com.runwaysdk.business.Entity.getAllInstances(query, sortAttribute, ascending, pageSize, pageNumber);
    return query;
  }
  
  public gov.geoplatform.uasdm.bus.Mission getParent()
  {
    return (gov.geoplatform.uasdm.bus.Mission) super.getParent();
  }
  
  public gov.geoplatform.uasdm.bus.Collection getChild()
  {
    return (gov.geoplatform.uasdm.bus.Collection) super.getChild();
  }
  
  public static MissionHasCollection get(String oid)
  {
    return (MissionHasCollection) com.runwaysdk.business.Relationship.get(oid);
  }
  
  public static MissionHasCollection getByKey(String key)
  {
    return (MissionHasCollection) com.runwaysdk.business.Relationship.get(CLASS, key);
  }
  
  public static MissionHasCollection lock(java.lang.String oid)
  {
    MissionHasCollection _instance = MissionHasCollection.get(oid);
    _instance.lock();
    
    return _instance;
  }
  
  public static MissionHasCollection unlock(java.lang.String oid)
  {
    MissionHasCollection _instance = MissionHasCollection.get(oid);
    _instance.unlock();
    
    return _instance;
  }
  
  public String toString()
  {
    if (this.isNew())
    {
      return "New: "+ this.getClassDisplayLabel();
    }
    else
    {
      return super.toString();
    }
  }
}
