package gov.geoplatform.uasdm.bus;

@com.runwaysdk.business.ClassSignature(hash = -1613571845)
/**
 * This class is generated automatically.
 * DO NOT MAKE CHANGES TO IT - THEY WILL BE OVERWRITTEN
 * Custom business logic should be added to PrivilegeType.java
 *
 * @author Autogenerated by RunwaySDK
 */
public abstract class PrivilegeTypeBase extends com.runwaysdk.system.EnumerationMaster
{
  public final static String CLASS = "gov.geoplatform.uasdm.bus.PrivilegeType";
  private static final long serialVersionUID = -1613571845;
  
  public PrivilegeTypeBase()
  {
    super();
  }
  
  protected String getDeclaredType()
  {
    return CLASS;
  }
  
  public static PrivilegeTypeQuery getAllInstances(String sortAttribute, Boolean ascending, Integer pageSize, Integer pageNumber)
  {
    PrivilegeTypeQuery query = new PrivilegeTypeQuery(new com.runwaysdk.query.QueryFactory());
    com.runwaysdk.business.Entity.getAllInstances(query, sortAttribute, ascending, pageSize, pageNumber);
    return query;
  }
  
  public static PrivilegeType get(String oid)
  {
    return (PrivilegeType) com.runwaysdk.business.Business.get(oid);
  }
  
  public static PrivilegeType getByKey(String key)
  {
    return (PrivilegeType) com.runwaysdk.business.Business.get(CLASS, key);
  }
  
  public static PrivilegeType getEnumeration(String enumName)
  {
    return (PrivilegeType) com.runwaysdk.business.Business.getEnumeration(gov.geoplatform.uasdm.bus.PrivilegeType.CLASS ,enumName);
  }
  
  public static PrivilegeType lock(java.lang.String oid)
  {
    PrivilegeType _instance = PrivilegeType.get(oid);
    _instance.lock();
    
    return _instance;
  }
  
  public static PrivilegeType unlock(java.lang.String oid)
  {
    PrivilegeType _instance = PrivilegeType.get(oid);
    _instance.unlock();
    
    return _instance;
  }
  
  public String toString()
  {
    if (this.isNew())
    {
      return "New: "+ this.getClassDisplayLabel();
    }
    else
    {
      return super.toString();
    }
  }
}
