package gov.geoplatform.uasdm.bus;

@com.runwaysdk.business.ClassSignature(hash = -713470531)
/**
 * This class is generated automatically.
 * DO NOT MAKE CHANGES TO IT - THEY WILL BE OVERWRITTEN
 * Custom business logic should be added to Site.java
 *
 * @author Autogenerated by RunwaySDK
 */
public abstract class SiteBase extends gov.geoplatform.uasdm.bus.UasComponent
{
  public final static String CLASS = "gov.geoplatform.uasdm.bus.Site";
  private static final long serialVersionUID = -713470531;
  
  public SiteBase()
  {
    super();
  }
  
  protected String getDeclaredType()
  {
    return CLASS;
  }
  
  public static SiteQuery getAllInstances(String sortAttribute, Boolean ascending, Integer pageSize, Integer pageNumber)
  {
    SiteQuery query = new SiteQuery(new com.runwaysdk.query.QueryFactory());
    com.runwaysdk.business.Entity.getAllInstances(query, sortAttribute, ascending, pageSize, pageNumber);
    return query;
  }
  
  public gov.geoplatform.uasdm.bus.SiteHasProjects addProjects(gov.geoplatform.uasdm.bus.Project project)
  {
    return (gov.geoplatform.uasdm.bus.SiteHasProjects) addChild(project, gov.geoplatform.uasdm.bus.SiteHasProjects.CLASS);
  }
  
  public void removeProjects(gov.geoplatform.uasdm.bus.Project project)
  {
    removeAllChildren(project, gov.geoplatform.uasdm.bus.SiteHasProjects.CLASS);
  }
  
  @SuppressWarnings("unchecked")
  public com.runwaysdk.query.OIterator<? extends gov.geoplatform.uasdm.bus.Project> getAllProjects()
  {
    return (com.runwaysdk.query.OIterator<? extends gov.geoplatform.uasdm.bus.Project>) getChildren(gov.geoplatform.uasdm.bus.SiteHasProjects.CLASS);
  }
  
  @SuppressWarnings("unchecked")
  public com.runwaysdk.query.OIterator<? extends gov.geoplatform.uasdm.bus.SiteHasProjects> getAllProjectsRel()
  {
    return (com.runwaysdk.query.OIterator<? extends gov.geoplatform.uasdm.bus.SiteHasProjects>) getChildRelationships(gov.geoplatform.uasdm.bus.SiteHasProjects.CLASS);
  }
  
  @SuppressWarnings("unchecked")
  public gov.geoplatform.uasdm.bus.SiteHasProjects getProjectsRel(gov.geoplatform.uasdm.bus.Project project)
  {
    com.runwaysdk.query.OIterator<? extends gov.geoplatform.uasdm.bus.SiteHasProjects> iterator = (com.runwaysdk.query.OIterator<? extends gov.geoplatform.uasdm.bus.SiteHasProjects>) getRelationshipsWithChild(project, gov.geoplatform.uasdm.bus.SiteHasProjects.CLASS);
    try
    {
      if (iterator.hasNext())
      {
        return iterator.next();
      }
      else
      {
        return null;
      }
    }
    finally
    {
      iterator.close();
    }
  }
  
  public static Site get(String oid)
  {
    return (Site) com.runwaysdk.business.Business.get(oid);
  }
  
  public static Site getByKey(String key)
  {
    return (Site) com.runwaysdk.business.Business.get(CLASS, key);
  }
  
  public static Site lock(java.lang.String oid)
  {
    Site _instance = Site.get(oid);
    _instance.lock();
    
    return _instance;
  }
  
  public static Site unlock(java.lang.String oid)
  {
    Site _instance = Site.get(oid);
    _instance.unlock();
    
    return _instance;
  }
  
  public String toString()
  {
    if (this.isNew())
    {
      return "New: "+ this.getClassDisplayLabel();
    }
    else
    {
      return super.toString();
    }
  }
}
