package gov.geoplatform.uasdm.odm;

@com.runwaysdk.business.ClassSignature(hash = -771633117)
/**
 * This class is generated automatically.
 * DO NOT MAKE CHANGES TO IT - THEY WILL BE OVERWRITTEN
 * Custom business logic should be added to ImageryODMProcessingTask.java
 *
 * @author Autogenerated by RunwaySDK
 */
public class ImageryODMProcessingTaskQueryDTO extends gov.geoplatform.uasdm.bus.ImageryWorkflowTaskQueryDTO
{
private static final long serialVersionUID = -771633117;

  protected ImageryODMProcessingTaskQueryDTO(String type)
  {
    super(type);
  }

@SuppressWarnings("unchecked")
public java.util.List<? extends gov.geoplatform.uasdm.odm.ImageryODMProcessingTaskDTO> getResultSet()
{
  return (java.util.List<? extends gov.geoplatform.uasdm.odm.ImageryODMProcessingTaskDTO>)super.getResultSet();
}
}
