package gov.geoplatform.uasdm.odm;

@com.runwaysdk.business.ClassSignature(hash = -776943006)
/**
 * This class is generated automatically.
 * DO NOT MAKE CHANGES TO IT - THEY WILL BE OVERWRITTEN
 * Custom business logic should be added to ODMProcessingTask.java
 *
 * @author Autogenerated by RunwaySDK
 */
public  class ODMProcessingTaskQuery extends gov.geoplatform.uasdm.bus.WorkflowTaskQuery

{

  public ODMProcessingTaskQuery(com.runwaysdk.query.QueryFactory componentQueryFactory)
  {
    super(componentQueryFactory);
    if (this.getComponentQuery() == null)
    {
      com.runwaysdk.business.BusinessQuery businessQuery = componentQueryFactory.businessQuery(this.getClassType());

       this.setBusinessQuery(businessQuery);
    }
  }

  public ODMProcessingTaskQuery(com.runwaysdk.query.ValueQuery valueQuery)
  {
    super(valueQuery);
    if (this.getComponentQuery() == null)
    {
      com.runwaysdk.business.BusinessQuery businessQuery = new com.runwaysdk.business.BusinessQuery(valueQuery, this.getClassType());

       this.setBusinessQuery(businessQuery);
    }
  }

  public String getClassType()
  {
    return gov.geoplatform.uasdm.odm.ODMProcessingTask.CLASS;
  }
  public com.runwaysdk.query.SelectableChar getConfigurationJson()
  {
    return getConfigurationJson(null);

  }
 
  public com.runwaysdk.query.SelectableChar getConfigurationJson(String alias)
  {
    return (com.runwaysdk.query.SelectableChar)this.getComponentQuery().get(gov.geoplatform.uasdm.odm.ODMProcessingTask.CONFIGURATIONJSON, alias, null);

  }
 
  public com.runwaysdk.query.SelectableChar getConfigurationJson(String alias, String displayLabel)
  {
    return (com.runwaysdk.query.SelectableChar)this.getComponentQuery().get(gov.geoplatform.uasdm.odm.ODMProcessingTask.CONFIGURATIONJSON, alias, displayLabel);

  }
  public com.runwaysdk.query.SelectableChar getFilePrefix()
  {
    return getFilePrefix(null);

  }
 
  public com.runwaysdk.query.SelectableChar getFilePrefix(String alias)
  {
    return (com.runwaysdk.query.SelectableChar)this.getComponentQuery().get(gov.geoplatform.uasdm.odm.ODMProcessingTask.FILEPREFIX, alias, null);

  }
 
  public com.runwaysdk.query.SelectableChar getFilePrefix(String alias, String displayLabel)
  {
    return (com.runwaysdk.query.SelectableChar)this.getComponentQuery().get(gov.geoplatform.uasdm.odm.ODMProcessingTask.FILEPREFIX, alias, displayLabel);

  }
  public com.runwaysdk.query.SelectableChar getOdmOutput()
  {
    return getOdmOutput(null);

  }
 
  public com.runwaysdk.query.SelectableChar getOdmOutput(String alias)
  {
    return (com.runwaysdk.query.SelectableChar)this.getComponentQuery().get(gov.geoplatform.uasdm.odm.ODMProcessingTask.ODMOUTPUT, alias, null);

  }
 
  public com.runwaysdk.query.SelectableChar getOdmOutput(String alias, String displayLabel)
  {
    return (com.runwaysdk.query.SelectableChar)this.getComponentQuery().get(gov.geoplatform.uasdm.odm.ODMProcessingTask.ODMOUTPUT, alias, displayLabel);

  }
  public com.runwaysdk.query.SelectableChar getOdmUUID()
  {
    return getOdmUUID(null);

  }
 
  public com.runwaysdk.query.SelectableChar getOdmUUID(String alias)
  {
    return (com.runwaysdk.query.SelectableChar)this.getComponentQuery().get(gov.geoplatform.uasdm.odm.ODMProcessingTask.ODMUUID, alias, null);

  }
 
  public com.runwaysdk.query.SelectableChar getOdmUUID(String alias, String displayLabel)
  {
    return (com.runwaysdk.query.SelectableChar)this.getComponentQuery().get(gov.geoplatform.uasdm.odm.ODMProcessingTask.ODMUUID, alias, displayLabel);

  }
  public com.runwaysdk.query.SelectableChar getProcessFilenameArray()
  {
    return getProcessFilenameArray(null);

  }
 
  public com.runwaysdk.query.SelectableChar getProcessFilenameArray(String alias)
  {
    return (com.runwaysdk.query.SelectableChar)this.getComponentQuery().get(gov.geoplatform.uasdm.odm.ODMProcessingTask.PROCESSFILENAMEARRAY, alias, null);

  }
 
  public com.runwaysdk.query.SelectableChar getProcessFilenameArray(String alias, String displayLabel)
  {
    return (com.runwaysdk.query.SelectableChar)this.getComponentQuery().get(gov.geoplatform.uasdm.odm.ODMProcessingTask.PROCESSFILENAMEARRAY, alias, displayLabel);

  }
  /**  
   * Returns an iterator of Business objects that match the query criteria specified
   * on this query object. 
   * @return iterator of Business objects that match the query criteria specified
   * on this query object.
   */
  public com.runwaysdk.query.OIterator<? extends ODMProcessingTask> getIterator()
  {
    this.checkNotUsedInValueQuery();
    String sqlStmt;
    if (_limit != null && _skip != null)
    {
      sqlStmt = this.getComponentQuery().getSQL(_limit, _skip);
    }
    else
    {
      sqlStmt = this.getComponentQuery().getSQL();
    }
    java.util.Map<String, com.runwaysdk.query.ColumnInfo> columnInfoMap = this.getComponentQuery().getColumnInfoMap();

    java.sql.ResultSet results = com.runwaysdk.dataaccess.database.Database.query(sqlStmt);
    return new com.runwaysdk.business.BusinessIterator<ODMProcessingTask>(this.getComponentQuery().getMdEntityIF(), columnInfoMap, results);
  }


/**
 * Interface that masks all type unsafe query methods and defines all type safe methods.
 * This type is used when a join is performed on this class as a reference.
 **/
  public interface ODMProcessingTaskQueryReferenceIF extends gov.geoplatform.uasdm.bus.WorkflowTaskQuery.WorkflowTaskQueryReferenceIF
  {

    public com.runwaysdk.query.SelectableChar getConfigurationJson();
    public com.runwaysdk.query.SelectableChar getConfigurationJson(String alias);
    public com.runwaysdk.query.SelectableChar getConfigurationJson(String alias, String displayLabel);
    public com.runwaysdk.query.SelectableChar getFilePrefix();
    public com.runwaysdk.query.SelectableChar getFilePrefix(String alias);
    public com.runwaysdk.query.SelectableChar getFilePrefix(String alias, String displayLabel);
    public com.runwaysdk.query.SelectableChar getOdmOutput();
    public com.runwaysdk.query.SelectableChar getOdmOutput(String alias);
    public com.runwaysdk.query.SelectableChar getOdmOutput(String alias, String displayLabel);
    public com.runwaysdk.query.SelectableChar getOdmUUID();
    public com.runwaysdk.query.SelectableChar getOdmUUID(String alias);
    public com.runwaysdk.query.SelectableChar getOdmUUID(String alias, String displayLabel);
    public com.runwaysdk.query.SelectableChar getProcessFilenameArray();
    public com.runwaysdk.query.SelectableChar getProcessFilenameArray(String alias);
    public com.runwaysdk.query.SelectableChar getProcessFilenameArray(String alias, String displayLabel);

    public com.runwaysdk.query.BasicCondition EQ(gov.geoplatform.uasdm.odm.ODMProcessingTask oDMProcessingTask);

    public com.runwaysdk.query.BasicCondition NE(gov.geoplatform.uasdm.odm.ODMProcessingTask oDMProcessingTask);

  }

/**
 * Implements type safe query methods.
 * This type is used when a join is performed on this class as a reference.
 **/
  public static class ODMProcessingTaskQueryReference extends gov.geoplatform.uasdm.bus.WorkflowTaskQuery.WorkflowTaskQueryReference
 implements ODMProcessingTaskQueryReferenceIF

  {

  public ODMProcessingTaskQueryReference(com.runwaysdk.dataaccess.MdAttributeRefDAOIF mdAttributeIF, String attributeNamespace, String definingTableName, String definingTableAlias, com.runwaysdk.dataaccess.MdBusinessDAOIF referenceMdBusinessIF, String referenceTableAlias, com.runwaysdk.query.ComponentQuery rootQuery, java.util.Set<com.runwaysdk.query.Join> tableJoinSet, String alias, String displayLabel)
  {
    super(mdAttributeIF, attributeNamespace, definingTableName, definingTableAlias, referenceMdBusinessIF, referenceTableAlias, rootQuery, tableJoinSet, alias, displayLabel);

  }


    public com.runwaysdk.query.BasicCondition EQ(gov.geoplatform.uasdm.odm.ODMProcessingTask oDMProcessingTask)
    {
      if(oDMProcessingTask == null) return this.EQ((java.lang.String)null);
      return this.EQ(oDMProcessingTask.getOid());
    }

    public com.runwaysdk.query.BasicCondition NE(gov.geoplatform.uasdm.odm.ODMProcessingTask oDMProcessingTask)
    {
      if(oDMProcessingTask == null) return this.NE((java.lang.String)null);
      return this.NE(oDMProcessingTask.getOid());
    }

  public com.runwaysdk.query.SelectableChar getConfigurationJson()
  {
    return getConfigurationJson(null);

  }
 
  public com.runwaysdk.query.SelectableChar getConfigurationJson(String alias)
  {
    return (com.runwaysdk.query.SelectableChar)this.get(gov.geoplatform.uasdm.odm.ODMProcessingTask.CONFIGURATIONJSON, alias, null);

  }
 
  public com.runwaysdk.query.SelectableChar getConfigurationJson(String alias, String displayLabel)
  {
    return (com.runwaysdk.query.SelectableChar)this.get(gov.geoplatform.uasdm.odm.ODMProcessingTask.CONFIGURATIONJSON, alias, displayLabel);

  }
  public com.runwaysdk.query.SelectableChar getFilePrefix()
  {
    return getFilePrefix(null);

  }
 
  public com.runwaysdk.query.SelectableChar getFilePrefix(String alias)
  {
    return (com.runwaysdk.query.SelectableChar)this.get(gov.geoplatform.uasdm.odm.ODMProcessingTask.FILEPREFIX, alias, null);

  }
 
  public com.runwaysdk.query.SelectableChar getFilePrefix(String alias, String displayLabel)
  {
    return (com.runwaysdk.query.SelectableChar)this.get(gov.geoplatform.uasdm.odm.ODMProcessingTask.FILEPREFIX, alias, displayLabel);

  }
  public com.runwaysdk.query.SelectableChar getOdmOutput()
  {
    return getOdmOutput(null);

  }
 
  public com.runwaysdk.query.SelectableChar getOdmOutput(String alias)
  {
    return (com.runwaysdk.query.SelectableChar)this.get(gov.geoplatform.uasdm.odm.ODMProcessingTask.ODMOUTPUT, alias, null);

  }
 
  public com.runwaysdk.query.SelectableChar getOdmOutput(String alias, String displayLabel)
  {
    return (com.runwaysdk.query.SelectableChar)this.get(gov.geoplatform.uasdm.odm.ODMProcessingTask.ODMOUTPUT, alias, displayLabel);

  }
  public com.runwaysdk.query.SelectableChar getOdmUUID()
  {
    return getOdmUUID(null);

  }
 
  public com.runwaysdk.query.SelectableChar getOdmUUID(String alias)
  {
    return (com.runwaysdk.query.SelectableChar)this.get(gov.geoplatform.uasdm.odm.ODMProcessingTask.ODMUUID, alias, null);

  }
 
  public com.runwaysdk.query.SelectableChar getOdmUUID(String alias, String displayLabel)
  {
    return (com.runwaysdk.query.SelectableChar)this.get(gov.geoplatform.uasdm.odm.ODMProcessingTask.ODMUUID, alias, displayLabel);

  }
  public com.runwaysdk.query.SelectableChar getProcessFilenameArray()
  {
    return getProcessFilenameArray(null);

  }
 
  public com.runwaysdk.query.SelectableChar getProcessFilenameArray(String alias)
  {
    return (com.runwaysdk.query.SelectableChar)this.get(gov.geoplatform.uasdm.odm.ODMProcessingTask.PROCESSFILENAMEARRAY, alias, null);

  }
 
  public com.runwaysdk.query.SelectableChar getProcessFilenameArray(String alias, String displayLabel)
  {
    return (com.runwaysdk.query.SelectableChar)this.get(gov.geoplatform.uasdm.odm.ODMProcessingTask.PROCESSFILENAMEARRAY, alias, displayLabel);

  }
  }

/**
 * Interface that masks all type unsafe query methods and defines all type safe methods.
 * This type is used when a join is performed on this class as a reference.
 **/
  public interface ODMProcessingTaskQueryMultiReferenceIF extends gov.geoplatform.uasdm.bus.WorkflowTaskQuery.WorkflowTaskQueryMultiReferenceIF
  {

    public com.runwaysdk.query.SelectableChar getConfigurationJson();
    public com.runwaysdk.query.SelectableChar getConfigurationJson(String alias);
    public com.runwaysdk.query.SelectableChar getConfigurationJson(String alias, String displayLabel);
    public com.runwaysdk.query.SelectableChar getFilePrefix();
    public com.runwaysdk.query.SelectableChar getFilePrefix(String alias);
    public com.runwaysdk.query.SelectableChar getFilePrefix(String alias, String displayLabel);
    public com.runwaysdk.query.SelectableChar getOdmOutput();
    public com.runwaysdk.query.SelectableChar getOdmOutput(String alias);
    public com.runwaysdk.query.SelectableChar getOdmOutput(String alias, String displayLabel);
    public com.runwaysdk.query.SelectableChar getOdmUUID();
    public com.runwaysdk.query.SelectableChar getOdmUUID(String alias);
    public com.runwaysdk.query.SelectableChar getOdmUUID(String alias, String displayLabel);
    public com.runwaysdk.query.SelectableChar getProcessFilenameArray();
    public com.runwaysdk.query.SelectableChar getProcessFilenameArray(String alias);
    public com.runwaysdk.query.SelectableChar getProcessFilenameArray(String alias, String displayLabel);

    public com.runwaysdk.query.Condition containsAny(gov.geoplatform.uasdm.odm.ODMProcessingTask ... oDMProcessingTask);
    public com.runwaysdk.query.Condition notContainsAny(gov.geoplatform.uasdm.odm.ODMProcessingTask ... oDMProcessingTask);
    public com.runwaysdk.query.Condition containsAll(gov.geoplatform.uasdm.odm.ODMProcessingTask ... oDMProcessingTask);
    public com.runwaysdk.query.Condition notContainsAll(gov.geoplatform.uasdm.odm.ODMProcessingTask ... oDMProcessingTask);
    public com.runwaysdk.query.Condition containsExactly(gov.geoplatform.uasdm.odm.ODMProcessingTask ... oDMProcessingTask);
  }

/**
 * Implements type safe query methods.
 * This type is used when a join is performed on this class as a reference.
 **/
  public static class ODMProcessingTaskQueryMultiReference extends gov.geoplatform.uasdm.bus.WorkflowTaskQuery.WorkflowTaskQueryMultiReference
 implements ODMProcessingTaskQueryMultiReferenceIF

  {

  public ODMProcessingTaskQueryMultiReference(com.runwaysdk.dataaccess.MdAttributeMultiReferenceDAOIF mdAttributeIF, String attributeNamespace, String definingTableName, String definingTableAlias, String mdMultiReferenceTableName, com.runwaysdk.dataaccess.MdBusinessDAOIF referenceMdBusinessIF, String referenceTableAlias, com.runwaysdk.query.ComponentQuery rootQuery, java.util.Set<com.runwaysdk.query.Join> tableJoinSet, String alias, String displayLabel)
  {
    super(mdAttributeIF, attributeNamespace, definingTableName, definingTableAlias, mdMultiReferenceTableName, referenceMdBusinessIF, referenceTableAlias, rootQuery, tableJoinSet, alias, displayLabel);

  }



    public com.runwaysdk.query.Condition containsAny(gov.geoplatform.uasdm.odm.ODMProcessingTask ... oDMProcessingTask)  {

      String[] itemIdArray = new String[oDMProcessingTask.length]; 

      for (int i=0; i<oDMProcessingTask.length; i++)
      {
        itemIdArray[i] = oDMProcessingTask[i].getOid();
      }

      return this.containsAny(itemIdArray);
  }

    public com.runwaysdk.query.Condition notContainsAny(gov.geoplatform.uasdm.odm.ODMProcessingTask ... oDMProcessingTask)  {

      String[] itemIdArray = new String[oDMProcessingTask.length]; 

      for (int i=0; i<oDMProcessingTask.length; i++)
      {
        itemIdArray[i] = oDMProcessingTask[i].getOid();
      }

      return this.notContainsAny(itemIdArray);
  }

    public com.runwaysdk.query.Condition containsAll(gov.geoplatform.uasdm.odm.ODMProcessingTask ... oDMProcessingTask)  {

      String[] itemIdArray = new String[oDMProcessingTask.length]; 

      for (int i=0; i<oDMProcessingTask.length; i++)
      {
        itemIdArray[i] = oDMProcessingTask[i].getOid();
      }

      return this.containsAll(itemIdArray);
  }

    public com.runwaysdk.query.Condition notContainsAll(gov.geoplatform.uasdm.odm.ODMProcessingTask ... oDMProcessingTask)  {

      String[] itemIdArray = new String[oDMProcessingTask.length]; 

      for (int i=0; i<oDMProcessingTask.length; i++)
      {
        itemIdArray[i] = oDMProcessingTask[i].getOid();
      }

      return this.notContainsAll(itemIdArray);
  }

    public com.runwaysdk.query.Condition containsExactly(gov.geoplatform.uasdm.odm.ODMProcessingTask ... oDMProcessingTask)  {

      String[] itemIdArray = new String[oDMProcessingTask.length]; 

      for (int i=0; i<oDMProcessingTask.length; i++)
      {
        itemIdArray[i] = oDMProcessingTask[i].getOid();
      }

      return this.containsExactly(itemIdArray);
  }
  public com.runwaysdk.query.SelectableChar getConfigurationJson()
  {
    return getConfigurationJson(null);

  }
 
  public com.runwaysdk.query.SelectableChar getConfigurationJson(String alias)
  {
    return (com.runwaysdk.query.SelectableChar)this.get(gov.geoplatform.uasdm.odm.ODMProcessingTask.CONFIGURATIONJSON, alias, null);

  }
 
  public com.runwaysdk.query.SelectableChar getConfigurationJson(String alias, String displayLabel)
  {
    return (com.runwaysdk.query.SelectableChar)this.get(gov.geoplatform.uasdm.odm.ODMProcessingTask.CONFIGURATIONJSON, alias, displayLabel);

  }
  public com.runwaysdk.query.SelectableChar getFilePrefix()
  {
    return getFilePrefix(null);

  }
 
  public com.runwaysdk.query.SelectableChar getFilePrefix(String alias)
  {
    return (com.runwaysdk.query.SelectableChar)this.get(gov.geoplatform.uasdm.odm.ODMProcessingTask.FILEPREFIX, alias, null);

  }
 
  public com.runwaysdk.query.SelectableChar getFilePrefix(String alias, String displayLabel)
  {
    return (com.runwaysdk.query.SelectableChar)this.get(gov.geoplatform.uasdm.odm.ODMProcessingTask.FILEPREFIX, alias, displayLabel);

  }
  public com.runwaysdk.query.SelectableChar getOdmOutput()
  {
    return getOdmOutput(null);

  }
 
  public com.runwaysdk.query.SelectableChar getOdmOutput(String alias)
  {
    return (com.runwaysdk.query.SelectableChar)this.get(gov.geoplatform.uasdm.odm.ODMProcessingTask.ODMOUTPUT, alias, null);

  }
 
  public com.runwaysdk.query.SelectableChar getOdmOutput(String alias, String displayLabel)
  {
    return (com.runwaysdk.query.SelectableChar)this.get(gov.geoplatform.uasdm.odm.ODMProcessingTask.ODMOUTPUT, alias, displayLabel);

  }
  public com.runwaysdk.query.SelectableChar getOdmUUID()
  {
    return getOdmUUID(null);

  }
 
  public com.runwaysdk.query.SelectableChar getOdmUUID(String alias)
  {
    return (com.runwaysdk.query.SelectableChar)this.get(gov.geoplatform.uasdm.odm.ODMProcessingTask.ODMUUID, alias, null);

  }
 
  public com.runwaysdk.query.SelectableChar getOdmUUID(String alias, String displayLabel)
  {
    return (com.runwaysdk.query.SelectableChar)this.get(gov.geoplatform.uasdm.odm.ODMProcessingTask.ODMUUID, alias, displayLabel);

  }
  public com.runwaysdk.query.SelectableChar getProcessFilenameArray()
  {
    return getProcessFilenameArray(null);

  }
 
  public com.runwaysdk.query.SelectableChar getProcessFilenameArray(String alias)
  {
    return (com.runwaysdk.query.SelectableChar)this.get(gov.geoplatform.uasdm.odm.ODMProcessingTask.PROCESSFILENAMEARRAY, alias, null);

  }
 
  public com.runwaysdk.query.SelectableChar getProcessFilenameArray(String alias, String displayLabel)
  {
    return (com.runwaysdk.query.SelectableChar)this.get(gov.geoplatform.uasdm.odm.ODMProcessingTask.PROCESSFILENAMEARRAY, alias, displayLabel);

  }
  }
}
