package gov.geoplatform.uasdm.odm;

@com.runwaysdk.business.ClassSignature(hash = 1095514369)
/**
 * This class is generated automatically.
 * DO NOT MAKE CHANGES TO IT - THEY WILL BE OVERWRITTEN
 * Custom business logic should be added to ODMProcessingTask.java
 *
 * @author Autogenerated by RunwaySDK
 */
public abstract class ODMProcessingTaskBase extends gov.geoplatform.uasdm.bus.WorkflowTask
{
  public final static String CLASS = "gov.geoplatform.uasdm.odm.ODMProcessingTask";
  public static java.lang.String ODMUUID = "odmUUID";
  private static final long serialVersionUID = 1095514369;
  
  public ODMProcessingTaskBase()
  {
    super();
  }
  
  public String getOdmUUID()
  {
    return getValue(ODMUUID);
  }
  
  public void validateOdmUUID()
  {
    this.validateAttribute(ODMUUID);
  }
  
  public static com.runwaysdk.dataaccess.MdAttributeCharacterDAOIF getOdmUUIDMd()
  {
    com.runwaysdk.dataaccess.MdClassDAOIF mdClassIF = com.runwaysdk.dataaccess.metadata.MdClassDAO.getMdClassDAO(gov.geoplatform.uasdm.odm.ODMProcessingTask.CLASS);
    return (com.runwaysdk.dataaccess.MdAttributeCharacterDAOIF)mdClassIF.definesAttribute(ODMUUID);
  }
  
  public void setOdmUUID(String value)
  {
    if(value == null)
    {
      setValue(ODMUUID, "");
    }
    else
    {
      setValue(ODMUUID, value);
    }
  }
  
  protected String getDeclaredType()
  {
    return CLASS;
  }
  
  public static ODMProcessingTaskQuery getAllInstances(String sortAttribute, Boolean ascending, Integer pageSize, Integer pageNumber)
  {
    ODMProcessingTaskQuery query = new ODMProcessingTaskQuery(new com.runwaysdk.query.QueryFactory());
    com.runwaysdk.business.Entity.getAllInstances(query, sortAttribute, ascending, pageSize, pageNumber);
    return query;
  }
  
  public static ODMProcessingTask get(String oid)
  {
    return (ODMProcessingTask) com.runwaysdk.business.Business.get(oid);
  }
  
  public static ODMProcessingTask getByKey(String key)
  {
    return (ODMProcessingTask) com.runwaysdk.business.Business.get(CLASS, key);
  }
  
  public static ODMProcessingTask lock(java.lang.String oid)
  {
    ODMProcessingTask _instance = ODMProcessingTask.get(oid);
    _instance.lock();
    
    return _instance;
  }
  
  public static ODMProcessingTask unlock(java.lang.String oid)
  {
    ODMProcessingTask _instance = ODMProcessingTask.get(oid);
    _instance.unlock();
    
    return _instance;
  }
  
  public String toString()
  {
    if (this.isNew())
    {
      return "New: "+ this.getClassDisplayLabel();
    }
    else
    {
      return super.toString();
    }
  }
}
