/**
 * Copyright 2020 The Department of Interior
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package gov.geoplatform.uasdm.odm;

@com.runwaysdk.business.ClassSignature(hash = -1525877418)
/**
 * This class is generated automatically.
 * DO NOT MAKE CHANGES TO IT - THEY WILL BE OVERWRITTEN
 * Custom business logic should be added to ODMUploadTask.java
 *
 * @author Autogenerated by RunwaySDK
 */
public  class ODMUploadTaskQuery extends gov.geoplatform.uasdm.bus.WorkflowTaskQuery

{

  public ODMUploadTaskQuery(com.runwaysdk.query.QueryFactory componentQueryFactory)
  {
    super(componentQueryFactory);
    if (this.getComponentQuery() == null)
    {
      com.runwaysdk.business.BusinessQuery businessQuery = componentQueryFactory.businessQuery(this.getClassType());

       this.setBusinessQuery(businessQuery);
    }
  }

  public ODMUploadTaskQuery(com.runwaysdk.query.ValueQuery valueQuery)
  {
    super(valueQuery);
    if (this.getComponentQuery() == null)
    {
      com.runwaysdk.business.BusinessQuery businessQuery = new com.runwaysdk.business.BusinessQuery(valueQuery, this.getClassType());

       this.setBusinessQuery(businessQuery);
    }
  }

  public String getClassType()
  {
    return gov.geoplatform.uasdm.odm.ODMUploadTask.CLASS;
  }
  public com.runwaysdk.query.SelectableChar getOdmUUID()
  {
    return getOdmUUID(null);

  }
 
  public com.runwaysdk.query.SelectableChar getOdmUUID(String alias)
  {
    return (com.runwaysdk.query.SelectableChar)this.getComponentQuery().get(gov.geoplatform.uasdm.odm.ODMUploadTask.ODMUUID, alias, null);

  }
 
  public com.runwaysdk.query.SelectableChar getOdmUUID(String alias, String displayLabel)
  {
    return (com.runwaysdk.query.SelectableChar)this.getComponentQuery().get(gov.geoplatform.uasdm.odm.ODMUploadTask.ODMUUID, alias, displayLabel);

  }
  public gov.geoplatform.uasdm.odm.ODMProcessingTaskQuery.ODMProcessingTaskQueryReferenceIF getProcessingTask()
  {
    return getProcessingTask(null);

  }
 
  public gov.geoplatform.uasdm.odm.ODMProcessingTaskQuery.ODMProcessingTaskQueryReferenceIF getProcessingTask(String alias)
  {

    com.runwaysdk.dataaccess.MdAttributeDAOIF mdAttributeIF = this.getComponentQuery().getMdAttributeROfromMap(gov.geoplatform.uasdm.odm.ODMUploadTask.PROCESSINGTASK);

    return (gov.geoplatform.uasdm.odm.ODMProcessingTaskQuery.ODMProcessingTaskQueryReferenceIF)this.getComponentQuery().internalAttributeFactory(gov.geoplatform.uasdm.odm.ODMUploadTask.PROCESSINGTASK, mdAttributeIF, this, alias, null);

  }
 
  public gov.geoplatform.uasdm.odm.ODMProcessingTaskQuery.ODMProcessingTaskQueryReferenceIF getProcessingTask(String alias, String displayLabel)
  {

    com.runwaysdk.dataaccess.MdAttributeDAOIF mdAttributeIF = this.getComponentQuery().getMdAttributeROfromMap(gov.geoplatform.uasdm.odm.ODMUploadTask.PROCESSINGTASK);

    return (gov.geoplatform.uasdm.odm.ODMProcessingTaskQuery.ODMProcessingTaskQueryReferenceIF)this.getComponentQuery().internalAttributeFactory(gov.geoplatform.uasdm.odm.ODMUploadTask.PROCESSINGTASK, mdAttributeIF, this, alias, displayLabel);

  }
  protected com.runwaysdk.query.AttributeReference referenceFactory( com.runwaysdk.dataaccess.MdAttributeRefDAOIF mdAttributeIF, String attributeNamespace, String definingTableName, String definingTableAlias,  com.runwaysdk.dataaccess.MdBusinessDAOIF referenceMdBusinessIF, String referenceTableAlias, com.runwaysdk.query.ComponentQuery rootQuery, java.util.Set<com.runwaysdk.query.Join> tableJoinSet, String userDefinedAlias, String userDefinedDisplayLabel)
  {
    String name = mdAttributeIF.definesAttribute();
    
    if (name.equals(gov.geoplatform.uasdm.odm.ODMUploadTask.PROCESSINGTASK)) 
    {
       return new gov.geoplatform.uasdm.odm.ODMProcessingTaskQuery.ODMProcessingTaskQueryReference((com.runwaysdk.dataaccess.MdAttributeRefDAOIF)mdAttributeIF, attributeNamespace, definingTableName, definingTableAlias, referenceMdBusinessIF, referenceTableAlias, rootQuery, tableJoinSet, userDefinedAlias, userDefinedDisplayLabel);
    }
    else 
    {
      return super.referenceFactory(mdAttributeIF, attributeNamespace, definingTableName, definingTableAlias, referenceMdBusinessIF, referenceTableAlias, rootQuery, tableJoinSet, userDefinedAlias, userDefinedDisplayLabel);
    }
  }

  /**  
   * Returns an iterator of Business objects that match the query criteria specified
   * on this query object. 
   * @return iterator of Business objects that match the query criteria specified
   * on this query object.
   */
  public com.runwaysdk.query.OIterator<? extends ODMUploadTask> getIterator()
  {
    this.checkNotUsedInValueQuery();
    String sqlStmt;
    if (_limit != null && _skip != null)
    {
      sqlStmt = this.getComponentQuery().getSQL(_limit, _skip);
    }
    else
    {
      sqlStmt = this.getComponentQuery().getSQL();
    }
    java.util.Map<String, com.runwaysdk.query.ColumnInfo> columnInfoMap = this.getComponentQuery().getColumnInfoMap();

    java.sql.ResultSet results = com.runwaysdk.dataaccess.database.Database.query(sqlStmt);
    return new com.runwaysdk.business.BusinessIterator<ODMUploadTask>(this.getComponentQuery().getMdEntityIF(), columnInfoMap, results);
  }


/**
 * Interface that masks all type unsafe query methods and defines all type safe methods.
 * This type is used when a join is performed on this class as a reference.
 **/
  public interface ODMUploadTaskQueryReferenceIF extends gov.geoplatform.uasdm.bus.WorkflowTaskQuery.WorkflowTaskQueryReferenceIF
  {

    public com.runwaysdk.query.SelectableChar getOdmUUID();
    public com.runwaysdk.query.SelectableChar getOdmUUID(String alias);
    public com.runwaysdk.query.SelectableChar getOdmUUID(String alias, String displayLabel);
    public gov.geoplatform.uasdm.odm.ODMProcessingTaskQuery.ODMProcessingTaskQueryReferenceIF getProcessingTask();
    public gov.geoplatform.uasdm.odm.ODMProcessingTaskQuery.ODMProcessingTaskQueryReferenceIF getProcessingTask(String alias);
    public gov.geoplatform.uasdm.odm.ODMProcessingTaskQuery.ODMProcessingTaskQueryReferenceIF getProcessingTask(String alias, String displayLabel);

    public com.runwaysdk.query.BasicCondition EQ(gov.geoplatform.uasdm.odm.ODMUploadTask oDMUploadTask);

    public com.runwaysdk.query.BasicCondition NE(gov.geoplatform.uasdm.odm.ODMUploadTask oDMUploadTask);

  }

/**
 * Implements type safe query methods.
 * This type is used when a join is performed on this class as a reference.
 **/
  public static class ODMUploadTaskQueryReference extends gov.geoplatform.uasdm.bus.WorkflowTaskQuery.WorkflowTaskQueryReference
 implements ODMUploadTaskQueryReferenceIF

  {

  public ODMUploadTaskQueryReference(com.runwaysdk.dataaccess.MdAttributeRefDAOIF mdAttributeIF, String attributeNamespace, String definingTableName, String definingTableAlias, com.runwaysdk.dataaccess.MdBusinessDAOIF referenceMdBusinessIF, String referenceTableAlias, com.runwaysdk.query.ComponentQuery rootQuery, java.util.Set<com.runwaysdk.query.Join> tableJoinSet, String alias, String displayLabel)
  {
    super(mdAttributeIF, attributeNamespace, definingTableName, definingTableAlias, referenceMdBusinessIF, referenceTableAlias, rootQuery, tableJoinSet, alias, displayLabel);

  }


    public com.runwaysdk.query.BasicCondition EQ(gov.geoplatform.uasdm.odm.ODMUploadTask oDMUploadTask)
    {
      if(oDMUploadTask == null) return this.EQ((java.lang.String)null);
      return this.EQ(oDMUploadTask.getOid());
    }

    public com.runwaysdk.query.BasicCondition NE(gov.geoplatform.uasdm.odm.ODMUploadTask oDMUploadTask)
    {
      if(oDMUploadTask == null) return this.NE((java.lang.String)null);
      return this.NE(oDMUploadTask.getOid());
    }

  public com.runwaysdk.query.SelectableChar getOdmUUID()
  {
    return getOdmUUID(null);

  }
 
  public com.runwaysdk.query.SelectableChar getOdmUUID(String alias)
  {
    return (com.runwaysdk.query.SelectableChar)this.get(gov.geoplatform.uasdm.odm.ODMUploadTask.ODMUUID, alias, null);

  }
 
  public com.runwaysdk.query.SelectableChar getOdmUUID(String alias, String displayLabel)
  {
    return (com.runwaysdk.query.SelectableChar)this.get(gov.geoplatform.uasdm.odm.ODMUploadTask.ODMUUID, alias, displayLabel);

  }
  public gov.geoplatform.uasdm.odm.ODMProcessingTaskQuery.ODMProcessingTaskQueryReferenceIF getProcessingTask()
  {
    return getProcessingTask(null);

  }
 
  public gov.geoplatform.uasdm.odm.ODMProcessingTaskQuery.ODMProcessingTaskQueryReferenceIF getProcessingTask(String alias)
  {
    return (gov.geoplatform.uasdm.odm.ODMProcessingTaskQuery.ODMProcessingTaskQueryReferenceIF)this.get(gov.geoplatform.uasdm.odm.ODMUploadTask.PROCESSINGTASK, alias, null);

  }
 
  public gov.geoplatform.uasdm.odm.ODMProcessingTaskQuery.ODMProcessingTaskQueryReferenceIF getProcessingTask(String alias, String displayLabel)
  {
    return (gov.geoplatform.uasdm.odm.ODMProcessingTaskQuery.ODMProcessingTaskQueryReferenceIF)this.get(gov.geoplatform.uasdm.odm.ODMUploadTask.PROCESSINGTASK,  alias, displayLabel);

  }
  protected com.runwaysdk.query.AttributeReference referenceFactory( com.runwaysdk.dataaccess.MdAttributeRefDAOIF mdAttributeIF, String attributeNamespace, String definingTableName, String definingTableAlias,  com.runwaysdk.dataaccess.MdBusinessDAOIF referenceMdBusinessIF, String referenceTableAlias, com.runwaysdk.query.ComponentQuery rootQuery, java.util.Set<com.runwaysdk.query.Join> tableJoinSet, String userDefinedAlias, String userDefinedDisplayLabel)
  {
    String name = mdAttributeIF.definesAttribute();
    
    if (name.equals(gov.geoplatform.uasdm.odm.ODMUploadTask.PROCESSINGTASK)) 
    {
       return new gov.geoplatform.uasdm.odm.ODMProcessingTaskQuery.ODMProcessingTaskQueryReference((com.runwaysdk.dataaccess.MdAttributeRefDAOIF)mdAttributeIF, attributeNamespace, definingTableName, definingTableAlias, referenceMdBusinessIF, referenceTableAlias, rootQuery, tableJoinSet, userDefinedAlias, userDefinedDisplayLabel);
    }
    else 
    {
      return super.referenceFactory(mdAttributeIF, attributeNamespace, definingTableName, definingTableAlias, referenceMdBusinessIF, referenceTableAlias, rootQuery, tableJoinSet, userDefinedAlias, userDefinedDisplayLabel);
    }
  }

  }

/**
 * Interface that masks all type unsafe query methods and defines all type safe methods.
 * This type is used when a join is performed on this class as a reference.
 **/
  public interface ODMUploadTaskQueryMultiReferenceIF extends gov.geoplatform.uasdm.bus.WorkflowTaskQuery.WorkflowTaskQueryMultiReferenceIF
  {

    public com.runwaysdk.query.SelectableChar getOdmUUID();
    public com.runwaysdk.query.SelectableChar getOdmUUID(String alias);
    public com.runwaysdk.query.SelectableChar getOdmUUID(String alias, String displayLabel);
    public gov.geoplatform.uasdm.odm.ODMProcessingTaskQuery.ODMProcessingTaskQueryReferenceIF getProcessingTask();
    public gov.geoplatform.uasdm.odm.ODMProcessingTaskQuery.ODMProcessingTaskQueryReferenceIF getProcessingTask(String alias);
    public gov.geoplatform.uasdm.odm.ODMProcessingTaskQuery.ODMProcessingTaskQueryReferenceIF getProcessingTask(String alias, String displayLabel);

    public com.runwaysdk.query.Condition containsAny(gov.geoplatform.uasdm.odm.ODMUploadTask ... oDMUploadTask);
    public com.runwaysdk.query.Condition notContainsAny(gov.geoplatform.uasdm.odm.ODMUploadTask ... oDMUploadTask);
    public com.runwaysdk.query.Condition containsAll(gov.geoplatform.uasdm.odm.ODMUploadTask ... oDMUploadTask);
    public com.runwaysdk.query.Condition notContainsAll(gov.geoplatform.uasdm.odm.ODMUploadTask ... oDMUploadTask);
    public com.runwaysdk.query.Condition containsExactly(gov.geoplatform.uasdm.odm.ODMUploadTask ... oDMUploadTask);
  }

/**
 * Implements type safe query methods.
 * This type is used when a join is performed on this class as a reference.
 **/
  public static class ODMUploadTaskQueryMultiReference extends gov.geoplatform.uasdm.bus.WorkflowTaskQuery.WorkflowTaskQueryMultiReference
 implements ODMUploadTaskQueryMultiReferenceIF

  {

  public ODMUploadTaskQueryMultiReference(com.runwaysdk.dataaccess.MdAttributeMultiReferenceDAOIF mdAttributeIF, String attributeNamespace, String definingTableName, String definingTableAlias, String mdMultiReferenceTableName, com.runwaysdk.dataaccess.MdBusinessDAOIF referenceMdBusinessIF, String referenceTableAlias, com.runwaysdk.query.ComponentQuery rootQuery, java.util.Set<com.runwaysdk.query.Join> tableJoinSet, String alias, String displayLabel)
  {
    super(mdAttributeIF, attributeNamespace, definingTableName, definingTableAlias, mdMultiReferenceTableName, referenceMdBusinessIF, referenceTableAlias, rootQuery, tableJoinSet, alias, displayLabel);

  }



    public com.runwaysdk.query.Condition containsAny(gov.geoplatform.uasdm.odm.ODMUploadTask ... oDMUploadTask)  {

      String[] itemIdArray = new String[oDMUploadTask.length]; 

      for (int i=0; i<oDMUploadTask.length; i++)
      {
        itemIdArray[i] = oDMUploadTask[i].getOid();
      }

      return this.containsAny(itemIdArray);
  }

    public com.runwaysdk.query.Condition notContainsAny(gov.geoplatform.uasdm.odm.ODMUploadTask ... oDMUploadTask)  {

      String[] itemIdArray = new String[oDMUploadTask.length]; 

      for (int i=0; i<oDMUploadTask.length; i++)
      {
        itemIdArray[i] = oDMUploadTask[i].getOid();
      }

      return this.notContainsAny(itemIdArray);
  }

    public com.runwaysdk.query.Condition containsAll(gov.geoplatform.uasdm.odm.ODMUploadTask ... oDMUploadTask)  {

      String[] itemIdArray = new String[oDMUploadTask.length]; 

      for (int i=0; i<oDMUploadTask.length; i++)
      {
        itemIdArray[i] = oDMUploadTask[i].getOid();
      }

      return this.containsAll(itemIdArray);
  }

    public com.runwaysdk.query.Condition notContainsAll(gov.geoplatform.uasdm.odm.ODMUploadTask ... oDMUploadTask)  {

      String[] itemIdArray = new String[oDMUploadTask.length]; 

      for (int i=0; i<oDMUploadTask.length; i++)
      {
        itemIdArray[i] = oDMUploadTask[i].getOid();
      }

      return this.notContainsAll(itemIdArray);
  }

    public com.runwaysdk.query.Condition containsExactly(gov.geoplatform.uasdm.odm.ODMUploadTask ... oDMUploadTask)  {

      String[] itemIdArray = new String[oDMUploadTask.length]; 

      for (int i=0; i<oDMUploadTask.length; i++)
      {
        itemIdArray[i] = oDMUploadTask[i].getOid();
      }

      return this.containsExactly(itemIdArray);
  }
  public com.runwaysdk.query.SelectableChar getOdmUUID()
  {
    return getOdmUUID(null);

  }
 
  public com.runwaysdk.query.SelectableChar getOdmUUID(String alias)
  {
    return (com.runwaysdk.query.SelectableChar)this.get(gov.geoplatform.uasdm.odm.ODMUploadTask.ODMUUID, alias, null);

  }
 
  public com.runwaysdk.query.SelectableChar getOdmUUID(String alias, String displayLabel)
  {
    return (com.runwaysdk.query.SelectableChar)this.get(gov.geoplatform.uasdm.odm.ODMUploadTask.ODMUUID, alias, displayLabel);

  }
  public gov.geoplatform.uasdm.odm.ODMProcessingTaskQuery.ODMProcessingTaskQueryReferenceIF getProcessingTask()
  {
    return getProcessingTask(null);

  }
 
  public gov.geoplatform.uasdm.odm.ODMProcessingTaskQuery.ODMProcessingTaskQueryReferenceIF getProcessingTask(String alias)
  {
    return (gov.geoplatform.uasdm.odm.ODMProcessingTaskQuery.ODMProcessingTaskQueryReferenceIF)this.get(gov.geoplatform.uasdm.odm.ODMUploadTask.PROCESSINGTASK, alias, null);

  }
 
  public gov.geoplatform.uasdm.odm.ODMProcessingTaskQuery.ODMProcessingTaskQueryReferenceIF getProcessingTask(String alias, String displayLabel)
  {
    return (gov.geoplatform.uasdm.odm.ODMProcessingTaskQuery.ODMProcessingTaskQueryReferenceIF)this.get(gov.geoplatform.uasdm.odm.ODMUploadTask.PROCESSINGTASK,  alias, displayLabel);

  }
  protected com.runwaysdk.query.AttributeReference referenceFactory( com.runwaysdk.dataaccess.MdAttributeRefDAOIF mdAttributeIF, String attributeNamespace, String definingTableName, String definingTableAlias,  com.runwaysdk.dataaccess.MdBusinessDAOIF referenceMdBusinessIF, String referenceTableAlias, com.runwaysdk.query.ComponentQuery rootQuery, java.util.Set<com.runwaysdk.query.Join> tableJoinSet, String userDefinedAlias, String userDefinedDisplayLabel)
  {
    String name = mdAttributeIF.definesAttribute();
    
    if (name.equals(gov.geoplatform.uasdm.odm.ODMUploadTask.PROCESSINGTASK)) 
    {
       return new gov.geoplatform.uasdm.odm.ODMProcessingTaskQuery.ODMProcessingTaskQueryReference((com.runwaysdk.dataaccess.MdAttributeRefDAOIF)mdAttributeIF, attributeNamespace, definingTableName, definingTableAlias, referenceMdBusinessIF, referenceTableAlias, rootQuery, tableJoinSet, userDefinedAlias, userDefinedDisplayLabel);
    }
    else 
    {
      return super.referenceFactory(mdAttributeIF, attributeNamespace, definingTableName, definingTableAlias, referenceMdBusinessIF, referenceTableAlias, rootQuery, tableJoinSet, userDefinedAlias, userDefinedDisplayLabel);
    }
  }

  }
}
