package gov.geoplatform.uasdm.bus;

@com.runwaysdk.business.ClassSignature(hash = 355654253)
/**
 * This class is generated automatically.
 * DO NOT MAKE CHANGES TO IT - THEY WILL BE OVERWRITTEN
 * Custom business logic should be added to ImageryWorkflowTask.java
 *
 * @author Autogenerated by RunwaySDK
 */
public class ImageryWorkflowTaskQueryDTO extends gov.geoplatform.uasdm.bus.AbstractWorkflowTaskQueryDTO
{
public static final long serialVersionUID = 355654253;

  protected ImageryWorkflowTaskQueryDTO(String type)
  {
    super(type);
  }

@SuppressWarnings("unchecked")
public java.util.List<? extends gov.geoplatform.uasdm.bus.ImageryWorkflowTaskDTO> getResultSet()
{
  return (java.util.List<? extends gov.geoplatform.uasdm.bus.ImageryWorkflowTaskDTO>)super.getResultSet();
}
}
