package gov.geoplatform.uasdm.bus;

@com.runwaysdk.business.ClassSignature(hash = 1576872743)
/**
 * This class is generated automatically.
 * DO NOT MAKE CHANGES TO IT - THEY WILL BE OVERWRITTEN
 * Custom business logic should be added to MissionHasCollection.java
 *
 * @author Autogenerated by RunwaySDK
 */
public class MissionHasCollectionQueryDTO extends gov.geoplatform.uasdm.bus.ComponentHasComponentQueryDTO
{
public static final long serialVersionUID = 1576872743;

  protected MissionHasCollectionQueryDTO(String type)
  {
    super(type);
  }

@SuppressWarnings("unchecked")
public java.util.List<? extends gov.geoplatform.uasdm.bus.MissionHasCollectionDTO> getResultSet()
{
  return (java.util.List<? extends gov.geoplatform.uasdm.bus.MissionHasCollectionDTO>)super.getResultSet();
}
}
