package gov.geoplatform.uasdm.bus;

@com.runwaysdk.business.ClassSignature(hash = 1965346072)
/**
 * This class is generated automatically.
 * DO NOT MAKE CHANGES TO IT - THEY WILL BE OVERWRITTEN
 * Custom business logic should be added to SiteHasProjects.java
 *
 * @author Autogenerated by RunwaySDK
 */
public class SiteHasProjectsQueryDTO extends gov.geoplatform.uasdm.bus.ComponentHasComponentQueryDTO
{
public static final long serialVersionUID = 1965346072;

  protected SiteHasProjectsQueryDTO(String type)
  {
    super(type);
  }

@SuppressWarnings("unchecked")
public java.util.List<? extends gov.geoplatform.uasdm.bus.SiteHasProjectsDTO> getResultSet()
{
  return (java.util.List<? extends gov.geoplatform.uasdm.bus.SiteHasProjectsDTO>)super.getResultSet();
}
}
