package gov.geoplatform.uasdm.datamanagement;

@com.runwaysdk.business.ClassSignature(hash = -100223116)
/**
 * This class is generated automatically.
 * DO NOT MAKE CHANGES TO IT - THEY WILL BE OVERWRITTEN
 * Custom business logic should be added to MissionHasCollection.java
 *
 * @author Autogenerated by RunwaySDK
 */
public class MissionHasCollectionQueryDTO extends gov.geoplatform.uasdm.datamanagement.ComponentHasComponentQueryDTO
{
private static final long serialVersionUID = -100223116;

  protected MissionHasCollectionQueryDTO(String type)
  {
    super(type);
  }

@SuppressWarnings("unchecked")
public java.util.List<? extends gov.geoplatform.uasdm.datamanagement.MissionHasCollectionDTO> getResultSet()
{
  return (java.util.List<? extends gov.geoplatform.uasdm.datamanagement.MissionHasCollectionDTO>)super.getResultSet();
}
}
