package gov.geoplatform.uasdm.datamanagement;

@com.runwaysdk.business.ClassSignature(hash = -800059498)
/**
 * This class is generated automatically.
 * DO NOT MAKE CHANGES TO IT - THEY WILL BE OVERWRITTEN
 * Custom business logic should be added to Project.java
 *
 * @author Autogenerated by RunwaySDK
 */
public class ProjectQueryDTO extends gov.geoplatform.uasdm.datamanagement.UasComponentQueryDTO
{
private static final long serialVersionUID = -800059498;

  protected ProjectQueryDTO(String type)
  {
    super(type);
  }

@SuppressWarnings("unchecked")
public java.util.List<? extends gov.geoplatform.uasdm.datamanagement.ProjectDTO> getResultSet()
{
  return (java.util.List<? extends gov.geoplatform.uasdm.datamanagement.ProjectDTO>)super.getResultSet();
}
}
