package gov.geoplatform.uasdm.datamanagement;

@com.runwaysdk.business.ClassSignature(hash = -1507738473)
/**
 * This class is generated automatically.
 * DO NOT MAKE CHANGES TO IT - THEY WILL BE OVERWRITTEN
 * Custom business logic should be added to SiteHasProjects.java
 *
 * @author Autogenerated by RunwaySDK
 */
public class SiteHasProjectsQueryDTO extends gov.geoplatform.uasdm.datamanagement.ComponentHasComponentQueryDTO
{
private static final long serialVersionUID = -1507738473;

  protected SiteHasProjectsQueryDTO(String type)
  {
    super(type);
  }

@SuppressWarnings("unchecked")
public java.util.List<? extends gov.geoplatform.uasdm.datamanagement.SiteHasProjectsDTO> getResultSet()
{
  return (java.util.List<? extends gov.geoplatform.uasdm.datamanagement.SiteHasProjectsDTO>)super.getResultSet();
}
}
