package gov.geoplatform.uasdm.graph;

@com.runwaysdk.business.ClassSignature(hash = -1915085003)
/**
 * This class is generated automatically.
 * DO NOT MAKE CHANGES TO IT - THEY WILL BE OVERWRITTEN
 * Custom business logic should be added to Product.java
 *
 * @author Autogenerated by RunwaySDK
 */
public abstract class ProductBase extends com.runwaysdk.business.graph.VertexObject
{
  public final static String CLASS = "gov.geoplatform.uasdm.graph.Product";
  public static java.lang.String BOUNDINGBOX = "boundingBox";
  public static java.lang.String LASTUPDATEDATE = "lastUpdateDate";
  public static java.lang.String NAME = "name";
  public static java.lang.String OID = "oid";
  public static java.lang.String PUBLISHED = "published";
  public static java.lang.String SEQ = "seq";
  private static final long serialVersionUID = -1915085003;
  
  public ProductBase()
  {
    super();
  }
  
  public String getBoundingBox()
  {
    return (String) this.getObjectValue(BOUNDINGBOX);
  }
  
  public static com.runwaysdk.dataaccess.MdAttributeTextDAOIF getBoundingBoxMd()
  {
    com.runwaysdk.dataaccess.MdClassDAOIF mdClassIF = com.runwaysdk.dataaccess.metadata.MdClassDAO.getMdClassDAO(gov.geoplatform.uasdm.graph.Product.CLASS);
    return (com.runwaysdk.dataaccess.MdAttributeTextDAOIF)mdClassIF.definesAttribute(BOUNDINGBOX);
  }
  
  public void setBoundingBox(String value)
  {
    this.setValue(BOUNDINGBOX, value);
  }
  
  public java.util.Date getLastUpdateDate()
  {
    return (java.util.Date) this.getObjectValue(LASTUPDATEDATE);
  }
  
  public static com.runwaysdk.dataaccess.MdAttributeDateTimeDAOIF getLastUpdateDateMd()
  {
    com.runwaysdk.dataaccess.MdClassDAOIF mdClassIF = com.runwaysdk.dataaccess.metadata.MdClassDAO.getMdClassDAO(gov.geoplatform.uasdm.graph.Product.CLASS);
    return (com.runwaysdk.dataaccess.MdAttributeDateTimeDAOIF)mdClassIF.definesAttribute(LASTUPDATEDATE);
  }
  
  public void setLastUpdateDate(java.util.Date value)
  {
    this.setValue(LASTUPDATEDATE, value);
  }
  
  public String getName()
  {
    return (String) this.getObjectValue(NAME);
  }
  
  public static com.runwaysdk.dataaccess.MdAttributeCharacterDAOIF getNameMd()
  {
    com.runwaysdk.dataaccess.MdClassDAOIF mdClassIF = com.runwaysdk.dataaccess.metadata.MdClassDAO.getMdClassDAO(gov.geoplatform.uasdm.graph.Product.CLASS);
    return (com.runwaysdk.dataaccess.MdAttributeCharacterDAOIF)mdClassIF.definesAttribute(NAME);
  }
  
  public void setName(String value)
  {
    this.setValue(NAME, value);
  }
  
  public String getOid()
  {
    return (String) this.getObjectValue(OID);
  }
  
  public static com.runwaysdk.dataaccess.MdAttributeUUIDDAOIF getOidMd()
  {
    com.runwaysdk.dataaccess.MdClassDAOIF mdClassIF = com.runwaysdk.dataaccess.metadata.MdClassDAO.getMdClassDAO(gov.geoplatform.uasdm.graph.Product.CLASS);
    return (com.runwaysdk.dataaccess.MdAttributeUUIDDAOIF)mdClassIF.definesAttribute(OID);
  }
  
  public Boolean getPublished()
  {
    return (Boolean) this.getObjectValue(PUBLISHED);
  }
  
  public static com.runwaysdk.dataaccess.MdAttributeBooleanDAOIF getPublishedMd()
  {
    com.runwaysdk.dataaccess.MdClassDAOIF mdClassIF = com.runwaysdk.dataaccess.metadata.MdClassDAO.getMdClassDAO(gov.geoplatform.uasdm.graph.Product.CLASS);
    return (com.runwaysdk.dataaccess.MdAttributeBooleanDAOIF)mdClassIF.definesAttribute(PUBLISHED);
  }
  
  public void setPublished(Boolean value)
  {
    this.setValue(PUBLISHED, value);
  }
  
  public Long getSeq()
  {
    return (Long) this.getObjectValue(SEQ);
  }
  
  public static com.runwaysdk.dataaccess.MdAttributeLongDAOIF getSeqMd()
  {
    com.runwaysdk.dataaccess.MdClassDAOIF mdClassIF = com.runwaysdk.dataaccess.metadata.MdClassDAO.getMdClassDAO(gov.geoplatform.uasdm.graph.Product.CLASS);
    return (com.runwaysdk.dataaccess.MdAttributeLongDAOIF)mdClassIF.definesAttribute(SEQ);
  }
  
  public void setSeq(Long value)
  {
    this.setValue(SEQ, value);
  }
  
  protected String getDeclaredType()
  {
    return CLASS;
  }
  
  public com.runwaysdk.business.graph.EdgeObject addProductHasDocumentChild(gov.geoplatform.uasdm.graph.Document document)
  {
    return super.addChild(document, "gov.geoplatform.uasdm.graph.ProductHasDocument");
  }
  
  public void removeProductHasDocumentChild(gov.geoplatform.uasdm.graph.Document document)
  {
    super.removeChild(document, "gov.geoplatform.uasdm.graph.ProductHasDocument");
  }
  
  @SuppressWarnings("unchecked")
  public java.util.List<gov.geoplatform.uasdm.graph.Document> getProductHasDocumentChildDocuments()
  {
    return super.getChildren("gov.geoplatform.uasdm.graph.ProductHasDocument",gov.geoplatform.uasdm.graph.Document.class);
  }
  
  public com.runwaysdk.business.graph.EdgeObject addComponentHasProductParent(gov.geoplatform.uasdm.graph.UasComponent uasComponent)
  {
    return super.addParent(uasComponent, "gov.geoplatform.uasdm.graph.ComponentHasProduct");
  }
  
  public void removeComponentHasProductParent(gov.geoplatform.uasdm.graph.UasComponent uasComponent)
  {
    super.removeParent(uasComponent, "gov.geoplatform.uasdm.graph.ComponentHasProduct");
  }
  
  @SuppressWarnings("unchecked")
  public java.util.List<gov.geoplatform.uasdm.graph.UasComponent> getComponentHasProductParentUasComponents()
  {
    return super.getParents("gov.geoplatform.uasdm.graph.ComponentHasProduct", gov.geoplatform.uasdm.graph.UasComponent.class);
  }
  
  public com.runwaysdk.business.graph.EdgeObject addDocumentGeneratedProductParent(gov.geoplatform.uasdm.graph.Document document)
  {
    return super.addParent(document, "gov.geoplatform.uasdm.graph.DocumentGeneratedProduct");
  }
  
  public void removeDocumentGeneratedProductParent(gov.geoplatform.uasdm.graph.Document document)
  {
    super.removeParent(document, "gov.geoplatform.uasdm.graph.DocumentGeneratedProduct");
  }
  
  @SuppressWarnings("unchecked")
  public java.util.List<gov.geoplatform.uasdm.graph.Document> getDocumentGeneratedProductParentDocuments()
  {
    return super.getParents("gov.geoplatform.uasdm.graph.DocumentGeneratedProduct", gov.geoplatform.uasdm.graph.Document.class);
  }
  
  public static Product get(String oid)
  {
    return (Product) com.runwaysdk.business.graph.VertexObject.get(CLASS, oid);
  }
  
  public String toString()
  {
    if (this.isNew())
    {
      return "New: "+ this.getClassDisplayLabel();
    }
    else
    {
      return super.toString();
    }
  }
}
