package gov.geoplatform.uasdm.graph;

@com.runwaysdk.business.ClassSignature(hash = -1899179853)
/**
 * This class is generated automatically.
 * DO NOT MAKE CHANGES TO IT - THEY WILL BE OVERWRITTEN
 * Custom business logic should be added to SynchronizationEdge.java
 *
 * @author Autogenerated by RunwaySDK
 */
public class SynchronizationEdgeQueryDTO extends com.runwaysdk.business.BusinessQueryDTO
{
@SuppressWarnings("unused")
private static final long serialVersionUID = -1899179853;

  protected SynchronizationEdgeQueryDTO(String type)
  {
    super(type);
  }

@SuppressWarnings("unchecked")
public java.util.List<? extends gov.geoplatform.uasdm.graph.SynchronizationEdgeDTO> getResultSet()
{
  return (java.util.List<? extends gov.geoplatform.uasdm.graph.SynchronizationEdgeDTO>)super.getResultSet();
}
}
