package gov.geoplatform.uasdm;

@com.runwaysdk.business.ClassSignature(hash = 1643264830)
/**
 * This class is generated automatically.
 * DO NOT MAKE CHANGES TO IT - THEY WILL BE OVERWRITTEN
 * Custom business logic should be added to CollectionStatus.java
 *
 * @author Autogenerated by RunwaySDK
 */
public class CollectionStatusQueryDTO extends com.runwaysdk.business.BusinessQueryDTO
{
@SuppressWarnings("unused")
private static final long serialVersionUID = 1643264830;

  protected CollectionStatusQueryDTO(String type)
  {
    super(type);
  }

@SuppressWarnings("unchecked")
public java.util.List<? extends gov.geoplatform.uasdm.CollectionStatusDTO> getResultSet()
{
  return (java.util.List<? extends gov.geoplatform.uasdm.CollectionStatusDTO>)super.getResultSet();
}
}
