package gov.geoplatform.uasdm;

@com.runwaysdk.business.ClassSignature(hash = 127015218)
/**
 * This class is generated automatically.
 * DO NOT MAKE CHANGES TO IT - THEY WILL BE OVERWRITTEN
 * Custom business logic should be added to GenericException.java
 *
 * @author Autogenerated by RunwaySDK
 */
public abstract class GenericExceptionBase extends com.runwaysdk.business.SmartException
{
  public final static String CLASS = "gov.geoplatform.uasdm.GenericException";
  public static java.lang.String OID = "oid";
  public static java.lang.String USERMESSAGE = "userMessage";
  private static final long serialVersionUID = 127015218;
  
  public GenericExceptionBase()
  {
    super();
  }
  
  public GenericExceptionBase(java.lang.String developerMessage)
  {
    super(developerMessage);
  }
  
  public GenericExceptionBase(java.lang.String developerMessage, java.lang.Throwable cause)
  {
    super(developerMessage, cause);
  }
  
  public GenericExceptionBase(java.lang.Throwable cause)
  {
    super(cause);
  }
  
  public String getOid()
  {
    return getValue(OID);
  }
  
  public void validateOid()
  {
    this.validateAttribute(OID);
  }
  
  public static com.runwaysdk.dataaccess.MdAttributeUUIDDAOIF getOidMd()
  {
    com.runwaysdk.dataaccess.MdClassDAOIF mdClassIF = com.runwaysdk.dataaccess.metadata.MdClassDAO.getMdClassDAO(gov.geoplatform.uasdm.GenericException.CLASS);
    return (com.runwaysdk.dataaccess.MdAttributeUUIDDAOIF)mdClassIF.definesAttribute(OID);
  }
  
  public String getUserMessage()
  {
    return getValue(USERMESSAGE);
  }
  
  public void validateUserMessage()
  {
    this.validateAttribute(USERMESSAGE);
  }
  
  public static com.runwaysdk.dataaccess.MdAttributeTextDAOIF getUserMessageMd()
  {
    com.runwaysdk.dataaccess.MdClassDAOIF mdClassIF = com.runwaysdk.dataaccess.metadata.MdClassDAO.getMdClassDAO(gov.geoplatform.uasdm.GenericException.CLASS);
    return (com.runwaysdk.dataaccess.MdAttributeTextDAOIF)mdClassIF.definesAttribute(USERMESSAGE);
  }
  
  public void setUserMessage(String value)
  {
    if(value == null)
    {
      setValue(USERMESSAGE, "");
    }
    else
    {
      setValue(USERMESSAGE, value);
    }
  }
  
  protected String getDeclaredType()
  {
    return CLASS;
  }
  
  public java.lang.String localize(java.util.Locale locale)
  {
    java.lang.String message = super.localize(locale);
    message = replace(message, "{oid}", this.getOid());
    message = replace(message, "{userMessage}", this.getUserMessage());
    return message;
  }
  
}
