package gov.geoplatform.uasdm;

@com.runwaysdk.business.ClassSignature(hash = 604113436)
/**
 * This class is generated automatically.
 * DO NOT MAKE CHANGES TO IT - THEY WILL BE OVERWRITTEN
 * Custom business logic should be added to OrganizationSynchronization.java
 *
 * @author Autogenerated by RunwaySDK
 */
public class OrganizationSynchronizationQueryDTO extends com.runwaysdk.business.BusinessQueryDTO
{
@SuppressWarnings("unused")
private static final long serialVersionUID = 604113436;

  protected OrganizationSynchronizationQueryDTO(String type)
  {
    super(type);
  }

@SuppressWarnings("unchecked")
public java.util.List<? extends gov.geoplatform.uasdm.OrganizationSynchronizationDTO> getResultSet()
{
  return (java.util.List<? extends gov.geoplatform.uasdm.OrganizationSynchronizationDTO>)super.getResultSet();
}
}
